import '../models/lesson_video.dart';

/// Complete, uncut publisher-hosted lectures, separate from 570 interactive
/// Academy modules. Titles, IDs, durations and source pages were reconciled
/// against the publisher's three public playlist pages on 2026-09-27.
/// This metadata check is not a theological endorsement of every lecture.
class AcademyLecture {
  final String youtubeId;
  final String title;
  final String category;
  final int durationSeconds;
  final String publisherPage;

  const AcademyLecture(this.youtubeId, this.title, this.category,
      this.durationSeconds, this.publisherPage);

  String get durationLabel =>
      '${durationSeconds ~/ 60}:${(durationSeconds % 60).toString().padLeft(2, '0')}';

  LessonVideo toPlayerVideo() => LessonVideo(
        id: 'academy-$youtubeId',
        lessonId: 'academy-lectures',
        title: title,
        topic: title,
        languageCode: 'ru',
        provider: LessonVideoProvider.youtubeNoCookie,
        embedUrl: 'https://www.youtube-nocookie.com/embed/$youtubeId',
        transcript:
            'Полная внешняя лекция на русском языке. Сверяй выводы с первоисточником и обсуждай религиозные вопросы с квалифицированным специалистом.',
        source: LessonVideoSource(
          title: title,
          publisher: 'Абу Ясин · Руслан Маликов',
          url: 'https://www.youtube.com/watch?v=$youtubeId',
        ),
        speaker: const LessonVideoSpeaker(
          name: 'Руслан Маликов',
          role: 'автор внешней русскоязычной лекции',
        ),
        rights: LessonVideoRights(
          holder: 'Абу Ясин · Руслан Маликов',
          basis: LessonVideoRightsBasis.platformEmbed,
          label: 'Официальный встроенный плеер · без скачивания и перемонтажа',
          evidenceUrl: publisherPage,
          confirmedAt: DateTime.utc(2026, 9, 27),
        ),
        review: LessonVideoReview(
          status: LessonVideoReviewStatus.approved,
          reviewer: 'Muslingo publisher-metadata check',
          standard:
              'Approved for optional source-labelled display only; religious content awaits independent expert review; no XP or completion awarded',
          reviewedAt: DateTime.utc(2026, 9, 27),
        ),
      );
}

class AcademyLectureCatalog {
  static const List<AcademyLecture> all = [
    AcademyLecture(
        "mjySnzjBeBY",
        "ВСТУПЛЕНИЕ к серии уроков \"Учимся читать Коран по-арабски\"",
        "reading",
        624,
        "https://abu-yasin.com/video/vstuplenie-k-serii-urokov-uchimsya-chitat-koran-po-arabski/"),
    AcademyLecture("o4oRsk4BIMU", "Урок № 1: \"Арабский алфавит\"", "reading",
        310, "https://abu-yasin.com/video/urok-1-arabskiy-alfavit/"),
    AcademyLecture("Q4PjIyBHTSw", "Урок № 2:  Буква \"Алиф\"  ( أ  )",
        "reading", 419, "https://abu-yasin.com/video/urok-2-bukva-alif/"),
    AcademyLecture("LjbsNdJnJlQ", "Урок № 3:  Буква \"Ра\"  - ( ر )", "reading",
        507, "https://abu-yasin.com/video/urok-3-bukva-ra/"),
    AcademyLecture("HxLbaC9shRg", "Урок № 4: Харакаты-огласовки", "reading",
        942, "https://abu-yasin.com/video/urok-4-harakaty-oglasovki/"),
    AcademyLecture(
        "_XnLh099IpA",
        "Урок №5: \"Закрепление темы харакатов\".",
        "reading",
        434,
        "https://abu-yasin.com/video/urok-5-zakreplenie-temy-harakatov/"),
    AcademyLecture(
        "m6d70M_Evs4",
        "Урок №6: Применение харакатов к буквам \"Ра\" - (ر ) и \"Алиф\" - ( أ )",
        "reading",
        607,
        "https://abu-yasin.com/video/urok-6-primenenie-harakatov-k-bukvam-ra-i-alif/"),
    AcademyLecture("bN_mxfBahEo", "Урок №7: Буква \"Зей\" - ( ز )", "reading",
        474, "https://abu-yasin.com/video/urok-7-bukva-zey/"),
    AcademyLecture("GtHxfgLr6Qw", "Урок №8: Буква \"Мим\" - ( م )", "reading",
        691, "https://abu-yasin.com/video/urok-8-bukva-mim/"),
    AcademyLecture("odW0pz1eDb4", "Урок №9: Буква \"Та\" - ( ت )", "reading",
        801, "https://abu-yasin.com/video/urok-9-bukva-ta/"),
    AcademyLecture("moVsbfqq5iw", "Урок №10: Буква \"Нун\" - ( ن )", "reading",
        746, "https://abu-yasin.com/video/urok-10-bukva-nun/"),
    AcademyLecture("6yQGUvS_Qbc", "Урок №11: Буква \"Йа\" - ( ي )", "reading",
        915, "https://abu-yasin.com/video/urok-11-bukva-ya/"),
    AcademyLecture("ktzza5_FuIQ", "Урок №12: Буква \"Ба\" - ( ب )", "reading",
        790, "https://abu-yasin.com/video/urok-12-bukva-ba/"),
    AcademyLecture(
        "VEwX71EuvXo",
        "Урок №13: Буквы [ ب - ت - ث - ن - ي ] Разница и сходство.",
        "reading",
        152,
        "https://abu-yasin.com/video/urok-13-bukvy-raznica-i-shodstvo/"),
    AcademyLecture("Hckut613qDo", "Урок №14: Буква \"Кяф\" - ( ك )", "reading",
        846, "https://abu-yasin.com/video/urok-14-bukva-kyaf/"),
    AcademyLecture("VoB84bYm2TM", "Урок №15: Буква \"Лям\" -  ( ل )", "reading",
        1017, "https://abu-yasin.com/video/urok-15-bukva-lyam/"),
    AcademyLecture("oTONa18LeQY", "Урок №16: Буква \"Вау\" - ( و  )", "reading",
        708, "https://abu-yasin.com/video/urok-16-bukva-vau/"),
    AcademyLecture("znJ_sMQgvY4", "Урок №17: Буква \"ha\" - ( هـ )", "reading",
        1042, "https://abu-yasin.com/video/urok-17-bukva-ha/"),
    AcademyLecture("y5vMrw9My4A", "Урок №18: \"МОТИВАЦИЯ\"", "reading", 512,
        "https://abu-yasin.com/video/urok-18-motivaciya/"),
    AcademyLecture("8o2UZtle-vM", "Урок №19: Буква \"Фа\" - ( ف )", "reading",
        541, "https://abu-yasin.com/video/urok-19-bukva-fa/"),
    AcademyLecture("XuvcrPknaiM", "Урок №20:  Буква \"Каф\" - ( ق )", "reading",
        760, "https://abu-yasin.com/video/urok-20-bukva-kaf/"),
    AcademyLecture(
        "H46SELvYrVw",
        "Урок №21: Буквы /Фа - ف / Коф - ق / Кяф - ك / Разница и сходство",
        "reading",
        308,
        "https://abu-yasin.com/video/urok-21-bukvy-fa-kof-kyaf-raznica-i-shodstvo/"),
    AcademyLecture("tLYwIV9nw7E", "Урок №22: Буква \"Шин\" - ( ش )", "reading",
        796, "https://abu-yasin.com/video/urok-22-bukva-shin/"),
    AcademyLecture("5lzGpSd_kqs", "Урок №23:  Буква \"Син\" - ( س )", "reading",
        832, "https://abu-yasin.com/video/urok-23-bukva-sin/"),
    AcademyLecture("7g71yKDV4Vw", "Урок № 24:  Буква \"Ҫа \" - ( ث )",
        "reading", 971, "https://abu-yasin.com/video/urok-24-bukva-a/"),
    AcademyLecture(
        "IUk-Zn4JfL8",
        "Урок №25: Пример практической работы с пройденными буквами",
        "reading",
        245,
        "https://abu-yasin.com/video/urok-25-primer-prakticheskoy-raboty-s-proydennymi-bukvami/"),
    AcademyLecture("rGF8zPyIi1k", "Урок № 26: Буква \"Сод\" - ( ص )", "reading",
        792, "https://abu-yasin.com/video/urok-26-bukva-sod/"),
    AcademyLecture(
        "1wauyLGz0qk",
        "Урок №27: Буквы / Син - س / Ҫа - ث / Сод - ص / Разница и сходство",
        "reading",
        350,
        "https://abu-yasin.com/video/urok-27-bukvy-sin-a-sod-raznica-i-shodstvo/"),
    AcademyLecture("hN3whZh9m6M", "Урок № 28: Буква \"То\" - ( ط )", "reading",
        922, "https://abu-yasin.com/video/urok-28-bukva-to/"),
    AcademyLecture("SVrZl4FJFdM", "Урок № 29: Буква \"Джим\" - ( ج )",
        "reading", 756, "https://abu-yasin.com/video/urok-29-bukva-dzhim/"),
    AcademyLecture("PhWz-YPjnd4", "Урок № 30: Буква \"Ẋо\" - ( خ )", "reading",
        430, "https://abu-yasin.com/video/urok-30-bukva-o/"),
    AcademyLecture("2zQlxXNxjQM", "Урок № 31: Буква \"Ха\" - ( ح )", "reading",
        639, "https://abu-yasin.com/video/urok-31-bukva-ha/"),
    AcademyLecture(
        "GALzOyNU4Go",
        "Урок № 32: Буквы / ha - هـ / Ха - ح / Ẋо - خ / Разница и сходство.",
        "reading",
        500,
        "https://abu-yasin.com/video/urok-32-bukvy-ha-ha-o-raznica-i-shodstvo/"),
    AcademyLecture("41VgnUihPJs", "Урок № 33: Буква \"Гайн\" - ( غ )",
        "reading", 840, "https://abu-yasin.com/video/urok-33-bukva-gayn/"),
    AcademyLecture("sukS_YYlWrY", "Урок № 34: Буква \"Айн\" - ( ع ).",
        "reading", 839, "https://abu-yasin.com/video/urok-34-bukva-ayn/"),
    AcademyLecture("JaHb-VMs-QE", "Урок № 35: \"Даль\" - ( د )", "reading", 887,
        "https://abu-yasin.com/video/urok-35-dal/"),
    AcademyLecture("RWxuPNFVKdw", "Урок № 36: Буква \"Дод\" - ( ض ).",
        "reading", 583, "https://abu-yasin.com/video/urok-36-bukva-dod/"),
    AcademyLecture("JEW_ZlGmY4M", "Урок № 37: Буква \"Ҙаль\" - ( ذ ).",
        "reading", 403, "https://abu-yasin.com/video/urok-37-bukva-al/"),
    AcademyLecture("J6NmUun0Dk8", "Урок № 38: \"Зо\" - ( ظ ).", "reading", 520,
        "https://abu-yasin.com/video/urok-38-zo/"),
    AcademyLecture(
        "lMCu_d5xCTM",
        "Урок № 39: Буквы  / Зей - ز  / Ҙаль - ذ / Зо - ظ / Разница и сходство.",
        "reading",
        311,
        "https://abu-yasin.com/video/urok-39-bukvy-zey-al-zo-raznica-i-shodstvo/"),
    AcademyLecture("QTln15wk-Iw", "1) Буква  ( Ра -ر )", "reading", 1548,
        "https://abu-yasin.com/video/1-bukva-ra/"),
    AcademyLecture("bTg-IMfr3Nw", "2) Буква (Зей - ز )", "reading", 997,
        "https://abu-yasin.com/video/2-bukva-zey/"),
    AcademyLecture("sYWQlD-RQYI", "3) Буква (Мим - م )", "reading", 812,
        "https://abu-yasin.com/video/3-bukva-mim/"),
    AcademyLecture("O3BzF6mG95E", "4) Буква (Та - ت )", "reading", 650,
        "https://abu-yasin.com/video/4-bukva-ta/"),
    AcademyLecture("V_BRs8IWQU4", "5) Буква (Нун - ن )", "reading", 1081,
        "https://abu-yasin.com/video/5-bukva-nun/"),
    AcademyLecture("RnGoPBv5sFE", "7) Буква (Ба - ب)", "reading", 1321,
        "https://abu-yasin.com/video/7-bukva-ba/"),
    AcademyLecture("oUBZdhI_A_M", "6) Буква (Йа - ي)", "reading", 445,
        "https://abu-yasin.com/video/6-bukva-ya/"),
    AcademyLecture("dMzgXjVW12A", "8) Буква (Кяф - ك) махрадж", "reading", 896,
        "https://abu-yasin.com/video/8-bukva-kyaf-mahradzh/"),
    AcademyLecture("y6dZHrRqUo8", "9) Буква (Лям - ل) махрадж", "reading", 1108,
        "https://abu-yasin.com/video/9-bukva-lyam-mahradzh/"),
    AcademyLecture("fLGsApJAnpw", "10) Буква (Вау - و) махрадж", "reading", 786,
        "https://abu-yasin.com/video/10-bukva-vau-mahradzh/"),
    AcademyLecture("DnFtBYCludQ", "11) Буква (ha - هـ) махрадж", "reading", 219,
        "https://abu-yasin.com/video/11-bukva-ha-mahradzh/"),
    AcademyLecture("OIGd0UcMsnA", "12) Буква (Фа - ف) махрадж", "reading", 269,
        "https://abu-yasin.com/video/12-bukva-fa-mahradzh/"),
    AcademyLecture("hAXBcI93HR4", "13) Буква (Каф - ق) махрадж", "reading", 350,
        "https://abu-yasin.com/video/13-bukva-kaf-mahradzh/"),
    AcademyLecture("6UJFw51agQc", "15) Буква (Син - س)", "reading", 198,
        "https://abu-yasin.com/video/15-bukva-sin/"),
    AcademyLecture("mhTNvSNdJrA", "14) Буква (Шин - ش)", "reading", 265,
        "https://abu-yasin.com/video/14-bukva-shin/"),
    AcademyLecture("wv5vt9kTrE4", "16) Буква (Ҫа - ث)", "reading", 190,
        "https://abu-yasin.com/video/16-bukva-a/"),
    AcademyLecture("QspSllfG1Ts", "17) Буква (Сод - ص)", "reading", 193,
        "https://abu-yasin.com/video/17-bukva-sod/"),
    AcademyLecture("kae_nRHAmHU", "18) Буква (То - ط)", "reading", 1169,
        "https://abu-yasin.com/video/18-bukva-to/"),
    AcademyLecture("5J5A8ijuwUw", "19) Буква (Джим - ج)", "reading", 272,
        "https://abu-yasin.com/video/19-bukva-dzhim/"),
    AcademyLecture("6xc_q2eqyck", "20) Буква (Ẋо - خ) mp4", "reading", 81,
        "https://abu-yasin.com/video/20-bukva-o-mp4/"),
    AcademyLecture("tW3K5skwhHw", "21) Буква (Ха - ح)", "reading", 267,
        "https://abu-yasin.com/video/21-bukva-ha/"),
    AcademyLecture("4_jnj7EgDAE", "22) Буква (Гайн - غ )", "reading", 600,
        "https://abu-yasin.com/video/22-bukva-gayn/"),
    AcademyLecture("SfsOcu3sEeM", "23) Буква (Айн - ع )", "reading", 730,
        "https://abu-yasin.com/video/23-bukva-ayn/"),
    AcademyLecture("GyTJCl74u78", "24) Буква (Даль - د )", "reading", 270,
        "https://abu-yasin.com/video/24-bukva-dal/"),
    AcademyLecture("YFjNzxuuSrI", "25) Буква (Дод - ض )", "reading", 304,
        "https://abu-yasin.com/video/25-bukva-dod/"),
    AcademyLecture("ZjS2_XDW5vs", "26) Буква (Ҙаль - ذ )", "reading", 240,
        "https://abu-yasin.com/video/26-bukva-al/"),
    AcademyLecture("iDNTNo3MRw4", "27) Буква (Зо -  ظ)", "reading", 230,
        "https://abu-yasin.com/video/27-bukva-zo/"),
    AcademyLecture(
        "JkdZ5jIIbxE",
        "ВСТУПЛЕНИЕ к 2-му блоку \"Учимся читать Коран по-арабски\"",
        "reading",
        457,
        "https://abu-yasin.com/video/vstuplenie-k-2-mu-bloku-uchimsya-chitat-koran-po-arabski/"),
    AcademyLecture(
        "Y_sEbZ53oTA",
        "Урок № 1: Соединение \"Лям-Алиф\" ( لا )",
        "reading",
        180,
        "https://abu-yasin.com/video/urok-1-soedinenie-lyam-alif/"),
    AcademyLecture(
        "4n37DjhlqdQ",
        "Урок № 2: Правило начала и завершения в арабской речи / Не начинай сукуном, и не завершай харакатом",
        "reading",
        441,
        "https://abu-yasin.com/video/urok-2-pravilo-nachala-i-zaversheniya-v-arabskoy-rechi-ne-na/"),
    AcademyLecture(
        "p85pr6o2zVg",
        "Урок № 3: \"Та марбута\" ( ة )  (تَاء مَرْبُوطَة )",
        "reading",
        455,
        "https://abu-yasin.com/video/urok-3-ta-marbuta/"),
    AcademyLecture(
        "0TVrAdsTrrs",
        "Урок № 4: \"Мадд\" ( ّمَد ) - \"Протяжение Гласных\" (харакатов)",
        "reading",
        1305,
        "https://abu-yasin.com/video/urok-4-madd-protyazhenie-glasnyh-harakatov/"),
    AcademyLecture(
        "YqfHbkffG9M",
        "Урок № 5: Упражнения к теме \"Мадд\" (Протяжение гласных).",
        "reading",
        583,
        "https://abu-yasin.com/video/urok-5-uprazhneniya-k-teme-madd-protyazhenie-glasnyh/"),
    AcademyLecture(
        "fuP71zs8M5Y",
        "Урок № 6: Маленькие маддовые буквы (  و  -  ا  - ي  )",
        "reading",
        567,
        "https://abu-yasin.com/video/urok-6-malenkie-maddovye-bukvy/"),
    AcademyLecture(
        "2MqOtDfrTu8",
        "Урок № 7: \"Ташдид\" ( تَشْدِيد ) - \"Удвоенние\".",
        "reading",
        794,
        "https://abu-yasin.com/video/urok-7-tashdid-udvoennie/"),
    AcademyLecture(
        "WjMRN7MBSPA",
        "Урок № 8: \"Танвин\" ( تَنْوِينُ ) \"Добавление нун\" (Нунизация)",
        "reading",
        850,
        "https://abu-yasin.com/video/urok-8-tanvin-dobavlenie-nun-nunizaciya/"),
    AcademyLecture(
        "fCfquD-8hiA",
        "Урок № 9: Танвин+Ташдид (Практика)",
        "reading",
        260,
        "https://abu-yasin.com/video/urok-9-tanvin-tashdid-praktika/"),
    AcademyLecture("W2vhC26QweU", "Урок № 10: Арабские цифры", "reading", 347,
        "https://abu-yasin.com/video/urok-10-arabskie-cifry/"),
    AcademyLecture(
        "9A0-PBJqXzI",
        "Урок № 11: Определённость - Неопределённость / Артикль \"Аль\" ( اَلْ )",
        "reading",
        842,
        "https://abu-yasin.com/video/urok-11-opredelennost-neopredelennost-artikl-al/"),
    AcademyLecture(
        "gmMQufso6vY",
        "Урок № 12: Хамзат-уль-Кат ( هَمْزَة الْقَطْعِ ) \"Разделительная хамза\"",
        "reading",
        842,
        "https://abu-yasin.com/video/urok-12-hamzat-ul-kat-razdelitelnaya-hamza/"),
    AcademyLecture(
        "ajagLMaryzc",
        "Урок № 13:  Хамзат-уль-Васль ( هَمْزَة الْوَصْلِ ) \"Соединительная хамза\"",
        "reading",
        1128,
        "https://abu-yasin.com/video/urok-13-hamzat-ul-vasl-soedinitelnaya-hamza/"),
    AcademyLecture(
        "xBMZz7FilgA",
        "Урок № 14: Солнечные и лунные буквы (Правило взаимодействия c артиклем \" ْاَل \" )",
        "reading",
        787,
        "https://abu-yasin.com/video/urok-14-solnechnye-i-lunnye-bukvy-pravilo-vzaimodeystviya-c-/"),
    AcademyLecture(
        "VbBxrUt1BIU",
        "Урок № 15: Всё про артикль «Аль» ( اَلْ ) - итоги и новое",
        "reading",
        520,
        "https://abu-yasin.com/video/urok-15-vse-pro-artikl-al-itogi-i-novoe/"),
    AcademyLecture(
        "wslKJtaIa1k",
        "Урок № 16: Буква «Йа» ( ى ) после фатхи",
        "reading",
        191,
        "https://abu-yasin.com/video/urok-16-bukva-ya-posle-fathi/"),
    AcademyLecture(
        "SqciTWByMp0",
        "Урок № 17: Нечитаемые буквы в Коране",
        "reading",
        659,
        "https://abu-yasin.com/video/urok-17-nechitaemye-bukvy-v-korane/"),
    AcademyLecture("KUF5v0bO_8k", "Урок № 18: Танвин с кясрой", "reading", 875,
        "https://abu-yasin.com/video/urok-18-tanvin-s-kyasroy/"),
    AcademyLecture(
        "qjNbvDdv6Ks",
        "Урок № 19: Буква «Лям» ( ل ) в словах «الله» и «اللَّهُمَّ» / твёрдое и мягкое произношение",
        "reading",
        691,
        "https://abu-yasin.com/video/urok-19-bukva-lyam-v-slovah-i-tverdoe-i-myagkoe-proiznosheni/"),
    AcademyLecture(
        "RE5tyEcI7uU",
        "Урок  № 20: Сура \"аль-Кяфирун\" (الكَافِرُونَ) / Практическое зниятие (1)",
        "reading",
        637,
        "https://abu-yasin.com/video/urok-20-sura-al-kyafirun-prakticheskoe-zniyatie-1/"),
    AcademyLecture(
        "FnBQepcudgM",
        "Урок  № 21: Сура \"ан-Наср\" (النَّصْر) / Практическое зниятие (2)",
        "reading",
        907,
        "https://abu-yasin.com/video/urok-21-sura-an-nasr-prakticheskoe-zniyatie-2/"),
    AcademyLecture(
        "r2_pcaGjaUQ",
        "Урок  № 22: Сура \"аль-Масад\" (المَسَدُ) / Практическое зниятие (3)",
        "reading",
        727,
        "https://abu-yasin.com/video/urok-22-sura-al-masad-prakticheskoe-zniyatie-3/"),
    AcademyLecture(
        "i4XzKeFIpgw",
        "Урок  № 23: Сура \"аль-Ихляс\" (الإخْلَاصُ) /  Практическое занятие (4)",
        "reading",
        423,
        "https://abu-yasin.com/video/urok-23-sura-al-ihlyas-prakticheskoe-zanyatie-4/"),
    AcademyLecture(
        "sGu-QHuoJZc",
        "Урок  № 24: Сура \"аль-Фаляк\" (الفَلَقُ) /  Практическое занятие (5)",
        "reading",
        472,
        "https://abu-yasin.com/video/urok-24-sura-al-falyak-prakticheskoe-zanyatie-5/"),
    AcademyLecture(
        "LALopQeases",
        "Урок  № 25: Сура \"ан-Нас\" (النَّاسُ) /  Практическое занятие (6)",
        "reading",
        466,
        "https://abu-yasin.com/video/urok-25-sura-an-nas-prakticheskoe-zanyatie-6/"),
    AcademyLecture(
        "ej385XrDyU8",
        "ВСТУПЛЕНИЕ к 3-ему блоку серии «Учимся читать Коран по-арабски» - ТАДЖВИД",
        "reading",
        581,
        "https://abu-yasin.com/video/vstuplenie-k-3-emu-bloku-serii-uchimsya-chitat-koran-po-arab/"),
    AcademyLecture("N4ni0llsOj8", "Урок № 1: Что такое Таджвид?", "reading",
        948, "https://abu-yasin.com/video/urok-1-chto-takoe-tadzhvid/"),
    AcademyLecture("Yx6kjsaK8zw", "Урок № 2: Истиаза и Басмаля", "reading", 440,
        "https://abu-yasin.com/video/urok-2-istiaza-i-basmalya/"),
    AcademyLecture(
        "Lu5LPX53ETo",
        "Урок № 3: Калькаля - правило произнесения букв « قْ طْ بْ جْ  دْ» с сукуном",
        "reading",
        717,
        "https://abu-yasin.com/video/urok-3-kalkalya-pravilo-proizneseniya-bukv-s-sukunom/"),
    AcademyLecture(
        "YwU0x1F-po8",
        "Урок 4: Правила Мим-Сакина (المِيمُ  السَّاكِنَة)",
        "reading",
        1167,
        "https://abu-yasin.com/video/urok-4-pravila-mim-sakina/"),
    AcademyLecture(
        "a6yezQGVDS0",
        "Урок № 5: Практическое упражнение (1) (чтение 582 страницы Корана).",
        "reading",
        1121,
        "https://abu-yasin.com/video/urok-5-prakticheskoe-uprazhnenie-1-chtenie-582-stranicy-kora/"),
    AcademyLecture(
        "w27dNJuzHVc",
        "Урок № 6: «Изхар» (إِظْهَار) Ясное чтение /  1-ое правило Нун-Сакина и Танвина",
        "reading",
        1082,
        "https://abu-yasin.com/video/urok-6-izhar-yasnoe-chtenie-1-oe-pravilo-nun-sakina-i-tanvin/"),
    AcademyLecture(
        "QSMxEhMOuI0",
        "Урок № 7: Практическое упражнение (2) (Чтение 583-ей страницы Корана)",
        "reading",
        985,
        "https://abu-yasin.com/video/urok-7-prakticheskoe-uprazhnenie-2-chtenie-583-ey-stranicy-k/"),
    AcademyLecture(
        "YfSXw0Bg2fw",
        "Урок № 8: «Идгам» (إِدْغَام) Слитное чтение / 2-ое правило Нун-Сакина и Танвина",
        "reading",
        1055,
        "https://abu-yasin.com/video/urok-8-idgam-slitnoe-chtenie-2-oe-pravilo-nun-sakina-i-tanvi/"),
    AcademyLecture(
        "ntfZg_pvCyY",
        "Урок № 9: Практическое упражнение  (3) (Чтение 584-ой страницы Корана)",
        "reading",
        770,
        "https://abu-yasin.com/video/urok-9-prakticheskoe-uprazhnenie-3-chtenie-584-oy-stranicy-k/"),
    AcademyLecture(
        "9BLi8ZzDQDw",
        "Урок № 10: «Икляб» (إقْلَاب) «Замена» / 3- тье правило Нун-Сакина и Танвина",
        "reading",
        551,
        "https://abu-yasin.com/video/urok-10-iklyab-zamena-3-te-pravilo-nun-sakina-i-tanvina/"),
    AcademyLecture(
        "LV410zfhzik",
        "Урок № 11: Практическое упражнение (4) (Чтение 585-ой страницы Корана)",
        "reading",
        976,
        "https://abu-yasin.com/video/urok-11-prakticheskoe-uprazhnenie-4-chtenie-585-oy-stranicy-/"),
    AcademyLecture(
        "YdWsYhQ8iHI",
        "Урок № 12: «Ихфа» (إخْفَاء) Сокрытие / 4-ое правило Нун-Сакина и Танвина",
        "reading",
        773,
        "https://abu-yasin.com/video/urok-12-ihfa-sokrytie-4-oe-pravilo-nun-sakina-i-tanvina/"),
    AcademyLecture(
        "oGvjL0H_OvI",
        "Урок № 13: Практическое упражнение (5) (Чтение 586 страницы Корана)",
        "reading",
        899,
        "https://abu-yasin.com/video/urok-13-prakticheskoe-uprazhnenie-5-chtenie-586-stranicy-kor/"),
    AcademyLecture(
        "1CZN9hE84XQ",
        "Урок № 14: «Слияние похожих»  (Идгам мутамасилейн / إِدْغَامُ المُتَمَاثِلَيْنِ)",
        "reading",
        1315,
        "https://abu-yasin.com/video/urok-14-sliyanie-pohozhih-idgam-mutamasileyn/"),
    AcademyLecture(
        "wfqkcVzFU2s",
        "Урок № 15: Практическое упражнение (6) ( Чтение 587 страницы Корана)",
        "reading",
        782,
        "https://abu-yasin.com/video/urok-15-prakticheskoe-uprazhnenie-6-chtenie-587-stranicy-kor/"),
    AcademyLecture(
        "0qU-3WHwfN8",
        "Урок № 16: Мадд Асли    «Естественное протяжение» / اَلْمَدُّ اَلْأَصْلِي",
        "reading",
        312,
        "https://abu-yasin.com/video/urok-16-madd-asli-estestvennoe-protyazhenie/"),
    AcademyLecture(
        "weP7-2o3ALc",
        "Урок № 17: Практическое упражнение (7) ( Чтение 588- ой страницы Корана)",
        "reading",
        822,
        "https://abu-yasin.com/video/urok-17-prakticheskoe-uprazhnenie-7-chtenie-588-oy-stranicy-/"),
    AcademyLecture(
        "LkItu-ypJ48",
        "Урок № 18: Мадд муттасыль (Соединённый) Мадд мунфасыль (Разъединённый)",
        "reading",
        682,
        "https://abu-yasin.com/video/urok-18-madd-muttasyl-soedinennyy-madd-munfasyl-razedinennyy/"),
    AcademyLecture(
        "GNyx6-2I-bI",
        "Урок № 19: Практическое упражнение (8) (Чтение 589-ой страницы Корана)",
        "reading",
        901,
        "https://abu-yasin.com/video/urok-19-prakticheskoe-uprazhnenie-8-chtenie-589-oy-stranicy-/"),
    AcademyLecture(
        "W3xcX8seMMY",
        "Урок № 20: Мадд Лязим (Необходимое протяжение)",
        "reading",
        410,
        "https://abu-yasin.com/video/urok-20-madd-lyazim-neobhodimoe-protyazhenie/"),
    AcademyLecture(
        "qnND_iOU0Ic",
        "Урок № 21: Практическое упражнение (9) (Чтение 590-ой страницы Корана)",
        "reading",
        808,
        "https://abu-yasin.com/video/urok-21-prakticheskoe-uprazhnenie-9-chtenie-590-oy-stranicy-/"),
    AcademyLecture(
        "ck8WqTU0Wx4",
        "Урок № 22: Мадд «‘Арид ли-ссукун» ( Протяжение перед завершающим сукуном)",
        "reading",
        515,
        "https://abu-yasin.com/video/urok-22-madd-arid-li-ssukun-protyazhenie-pered-zavershayusch/"),
    AcademyLecture(
        "4TfObpAuLWc",
        "Урок № 23: Практическое упражнение (10) ( Чтение 591-ой страницы Корана)",
        "reading",
        851,
        "https://abu-yasin.com/video/urok-23-prakticheskoe-uprazhnenie-10-chtenie-591-oy-stranicy/"),
    AcademyLecture(
        "AeTICRtzYqQ",
        "Урок № 24: Мадд «Лин» (Мягкое протяжение)",
        "reading",
        512,
        "https://abu-yasin.com/video/urok-24-madd-lin-myagkoe-protyazhenie/"),
    AcademyLecture(
        "aQtidY_xTMg",
        "Урок № 25: Практическое упражнение (10) ( Чтение 592-ой страницы Корана)   + шпаргалка",
        "reading",
        999,
        "https://abu-yasin.com/video/urok-25-prakticheskoe-uprazhnenie-10-chtenie-592-oy-stranicy/"),
    AcademyLecture(
        "G2nkFFFxZpQ",
        "Урок № 26: «Мадд» - подведение итогов.",
        "reading",
        599,
        "https://abu-yasin.com/video/urok-26-madd-podvedenie-itogov/"),
    AcademyLecture(
        "A23cbbKBFOk",
        "Урок № 27: «Хуруф Мукаттаа» ч.1(Отдельные буквы) / Названия арабских букв",
        "reading",
        563,
        "https://abu-yasin.com/video/urok-27-huruf-mukattaa-ch-1-otdelnye-bukvy-nazvaniya-arabski/"),
    AcademyLecture(
        "Sm1vx0V_iY4",
        "Урок № 28: Хуруф Мукаттаа ч.2 (Отдельные буквы в начале некоторых сур)",
        "reading",
        1083,
        "https://abu-yasin.com/video/urok-28-huruf-mukattaa-ch-2-otdelnye-bukvy-v-nachale-nekotor/"),
    AcademyLecture(
        "lSEcBkmlppQ",
        "Урок № 29: Три чёрные точки в Коране",
        "reading",
        607,
        "https://abu-yasin.com/video/urok-29-tri-chernye-tochki-v-korane/"),
    AcademyLecture(
        "lxcly0ltFlg",
        "Урок № 30: Буква «Ра» ( ر ). Правила твёрдого и мягкого чтения.",
        "reading",
        1435,
        "https://abu-yasin.com/video/urok-30-bukva-ra-pravila-tverdogo-i-myagkogo-chteniya/"),
    AcademyLecture(
        "XcQQS4-GVZo",
        "Урок № 31: Практическое упражнение (12) (Чтение 593-ой страницы Корана)",
        "reading",
        694,
        "https://abu-yasin.com/video/urok-31-prakticheskoe-uprazhnenie-12-chtenie-593-oy-stranicy/"),
    AcademyLecture(
        "f0SO6wqovwI",
        "Урок № 32: Символы остановки и начала чтения в Коране",
        "reading",
        811,
        "https://abu-yasin.com/video/urok-32-simvoly-ostanovki-i-nachala-chteniya-v-korane/"),
    AcademyLecture(
        "0VTjxpSgz_0",
        "Урок № 33: Практическое упражнение (13) (Чтение 594-ой страницы Корана)",
        "reading",
        795,
        "https://abu-yasin.com/video/urok-33-prakticheskoe-uprazhnenie-13-chtenie-594-oy-stranicy/"),
    AcademyLecture(
        "DbZg24-Cmqo",
        "Урок № 34: Захват слова при необозначенной остановке.",
        "reading",
        591,
        "https://abu-yasin.com/video/urok-34-zahvat-slova-pri-neoboznachennoy-ostanovke/"),
    AcademyLecture(
        "hDPGnZ2JUbs",
        "Урок № 35: Практическое упражнение (14) (Чтение 595-ой страницы Корана)",
        "reading",
        714,
        "https://abu-yasin.com/video/urok-35-prakticheskoe-uprazhnenie-14-chtenie-595-oy-stranicy/"),
    AcademyLecture(
        "zSJJ2FNRyMY",
        "Урок № 36: Остановка на харакятах в необозначенных местах",
        "reading",
        677,
        "https://abu-yasin.com/video/urok-36-ostanovka-na-harakyatah-v-neoboznachennyh-mestah/"),
    AcademyLecture("osaFtQxvs6E", "Урок № 37: Остановка на хамзе", "reading",
        671, "https://abu-yasin.com/video/urok-37-ostanovka-na-hamze/"),
    AcademyLecture(
        "m6K-fi0QZ4k",
        "Урок № 38: Практическое упражнение (15) (Чтение 596-ой страницы Корана)",
        "reading",
        779,
        "https://abu-yasin.com/video/urok-38-prakticheskoe-uprazhnenie-15-chtenie-596-oy-stranicy/"),
    AcademyLecture("ZlYLGRIo52g", "Урок № 39: Остановка на шадде", "reading",
        685, "https://abu-yasin.com/video/urok-39-ostanovka-na-shadde/"),
    AcademyLecture(
        "ca0r2TlWt44",
        "Урок № 40: «Шесть алифов» или «Обнулённые буквы»",
        "reading",
        1081,
        "https://abu-yasin.com/video/urok-40-shest-alifov-ili-obnulennye-bukvy/"),
    AcademyLecture(
        "VGj2p6sBKJ4",
        "Урок № 41: Маленькая буковка «Син» (س) над и под буквой «Сод» (ص).",
        "reading",
        339,
        "https://abu-yasin.com/video/urok-41-malenkaya-bukovka-sin-nad-i-pod-bukvoy-sod/"),
    AcademyLecture(
        "rwJiRtwZzt4",
        "Урок № 42: Порядок в Коране  (часть 1 / Тартиб)    Джузы - Хизбы - Сумуны - Суры - Аяты",
        "reading",
        882,
        "https://abu-yasin.com/video/urok-42-poryadok-v-korane-chast-1-tartib-dzhuzy-hizby-sumuny/"),
    AcademyLecture(
        "c6Za32gU2V0",
        "Урок № 43: Порядок в Коране   (Часть 2 / Практика)",
        "reading",
        616,
        "https://abu-yasin.com/video/urok-43-poryadok-v-korane-chast-2-praktika/"),
    AcademyLecture(
        "JMESNFB-f0o",
        "Урок № 44: Практическое упражнение (16) (Чтение 597-ой страницы Корана)",
        "reading",
        781,
        "https://abu-yasin.com/video/urok-44-prakticheskoe-uprazhnenie-16-chtenie-597-oy-stranicy/"),
    AcademyLecture(
        "0HIC8L75KGw",
        "Урок № 45: Земной поклон во время чтения Корана  (Саджда Тилява / سَجْدَةُ التِّلَاوَةِ)",
        "reading",
        415,
        "https://abu-yasin.com/video/urok-45-zemnoy-poklon-vo-vremya-chteniya-korana-sadzhda-tily/"),
    AcademyLecture(
        "m8qr5q-lOSE",
        "Урок 1:  Вступление и Истиаза (УПК)",
        "meaning",
        1569,
        "https://abu-yasin.com/video/urok-1-vstuplenie-i-istiaza-upk/"),
    AcademyLecture("lO9mDJMiZ6E", "Урок 2:  Басмаля (УПК)", "meaning", 1482,
        "https://abu-yasin.com/video/urok-2-basmalya-upk/"),
    AcademyLecture("ZkhrwBYEJ7s", "Урок 3:  Фатиха, 2-3 аяты (УПК)", "meaning",
        1704, "https://abu-yasin.com/video/urok-3-fatiha-2-3-ayaty-upk/"),
    AcademyLecture("G1OoOq3xyhE", "Урок 4: Фатиха 4 аят (УПК)", "meaning", 1491,
        "https://abu-yasin.com/video/urok-4-fatiha-4-ayat-upk/"),
    AcademyLecture("06ZxkwV_xd8", "Урок 5: Фатиха 5 аят (УПК)", "meaning", 2006,
        "https://abu-yasin.com/video/urok-5-fatiha-5-ayat-upk/"),
    AcademyLecture(
        "Ltf63L9LmlA",
        "Урок 6: Фатиха 6 аят: «Веди нас прямым путём» (УПК)",
        "meaning",
        1768,
        "https://abu-yasin.com/video/urok-6-fatiha-6-ayat-vedi-nas-pryamym-putem-upk/"),
    AcademyLecture(
        "ba9Jl25s4jM",
        "Урок 7: Фатиха, 7 аят (ч.1): «Путём тех, кого Ты облагодетельствовал» (УПК)صراط الذين انعمت» عليهم»",
        "meaning",
        1526,
        "https://abu-yasin.com/video/urok-7-fatiha-7-ayat-ch-1-putem-teh-kogo-ty-oblagodetelstvov/"),
    AcademyLecture(
        "P499GN2Xol8",
        "Урок 8: Фатиха, 7 аят (ч.2): «… не путём тех, кто находится под гневом, и не путем заблудших» (УПК)",
        "meaning",
        1147,
        "https://abu-yasin.com/video/urok-8-fatiha-7-ayat-ch-2-ne-putem-teh-kto-nahoditsya-pod-gn/"),
    AcademyLecture(
        "ariKern9FRs",
        "Урок 9: “Единобожие  в суре Фатиха” (ч.1) Три вида  Таухида (УПК)",
        "meaning",
        2114,
        "https://abu-yasin.com/video/urok-9-edinobozhie-v-sure-fatiha-ch-1-tri-vida-tauhida-upk/"),
    AcademyLecture(
        "XHZglYSJlXs",
        "Урок 10: “Единобожие  в суре Фатиха” (ч.2) Имена и Качества (УПК)",
        "meaning",
        1401,
        "https://abu-yasin.com/video/urok-10-edinobozhie-v-sure-fatiha-ch-2-imena-i-kachestva-upk/"),
    AcademyLecture(
        "NiOSHI3jBWw",
        "Урок 11: “Экзамен по суре аль-Фатиха”  Проверь себя (УПК)",
        "meaning",
        497,
        "https://abu-yasin.com/video/urok-11-ekzamen-po-sure-al-fatiha-prover-sebya-upk/"),
    AcademyLecture(
        "x8KQ-c-bSCQ",
        "Урок 12: «ан-Нас», 1-3 аяты: «Скажи: Обращаюсь за защитой к Господу людей» (УПК)",
        "meaning",
        2047,
        "https://abu-yasin.com/video/urok-12-an-nas-1-3-ayaty-skazhi-obraschayus-za-zaschitoy-k-g/"),
    AcademyLecture(
        "niRhxokzt9g",
        "Урок 13: «ан-Нас», 4 аят: «… от зла шайтана наущающего» (УПК)",
        "meaning",
        1200,
        "https://abu-yasin.com/video/urok-13-an-nas-4-ayat-ot-zla-shaytana-nauschayuschego-upk/"),
    AcademyLecture(
        "rpvytkhUDaA",
        "Урок 14: «ан-Нас», 5-6 аят: «… которые наущают в сердцах» (УПК)",
        "meaning",
        1625,
        "https://abu-yasin.com/video/urok-14-an-nas-5-6-ayat-kotorye-nauschayut-v-serdcah-upk/"),
    AcademyLecture(
        "NhuQXATWUSc",
        "Урок 15: “Экзамен по суре ан-Нас («Люди») Проверь себя (УПК)",
        "meaning",
        617,
        "https://abu-yasin.com/video/urok-15-ekzamen-po-sure-an-nas-lyudi-prover-sebya-upk/"),
    AcademyLecture(
        "bTqICPRyUBI",
        "Урок 16: «аль-Фаляк», 1-3 аяты: «… к Господу рассвета» (УПК)",
        "meaning",
        1527,
        "https://abu-yasin.com/video/urok-16-al-falyak-1-3-ayaty-k-gospodu-rassveta-upk/"),
    AcademyLecture(
        "PU41KfC65sY",
        "Урок 17: «аль-Фаляк», 4-5 аяты: «… от колдуний и завистников» (УПК)",
        "meaning",
        1650,
        "https://abu-yasin.com/video/urok-17-al-falyak-4-5-ayaty-ot-kolduniy-i-zavistnikov-upk/"),
    AcademyLecture(
        "9_kWBcvTtCY",
        "Урок 18: «аль-Фаляк» Пару слов о колдунах и колдуньях (Дополнение) (УПК)",
        "meaning",
        1159,
        "https://abu-yasin.com/video/urok-18-al-falyak-paru-slov-o-koldunah-i-koldunyah-dopolneni/"),
    AcademyLecture(
        "io9pmNP8LCc",
        "Урок 19: “Экзамен по суре аль-Фаляк» («Рассвет») Проверь себя (УПК)",
        "meaning",
        540,
        "https://abu-yasin.com/video/urok-19-ekzamen-po-sure-al-falyak-rassvet-prover-sebya-upk/"),
    AcademyLecture(
        "DOrOO7PwZXI",
        "Урок 20: «аль-Ихляс», 1-2 аяты: «Аллах - Единственный, Аллах - Самад » (УПК)",
        "meaning",
        2115,
        "https://abu-yasin.com/video/urok-20-al-ihlyas-1-2-ayaty-allah-edinstvennyy-allah-samad-u/"),
    AcademyLecture(
        "U7oLKJduTX0",
        "Урок 21: «аль-Ихляс», 3-4 аяты: «Никого не рождал, и не был рождён. Нет Ему равных» (УПК)",
        "meaning",
        1329,
        "https://abu-yasin.com/video/urok-21-al-ihlyas-3-4-ayaty-nikogo-ne-rozhdal-i-ne-byl-rozhd/"),
    AcademyLecture(
        "r7WA-MVHG1c",
        "Урок 22: «аль-Ихляс» Экзамен (УПК) / Проверь себя по сурам 112-114 и Фатиха",
        "meaning",
        395,
        "https://abu-yasin.com/video/urok-22-al-ihlyas-ekzamen-upk-prover-sebya-po-suram-112-114-/"),
    AcademyLecture(
        "b6pO6c2cjB0",
        "Урок 23: «аль-Масад», 1 аят: «Да пропадут руки Абу Ляхаба» (УПК)",
        "meaning",
        1936,
        "https://abu-yasin.com/video/urok-23-al-masad-1-ayat-da-propadut-ruki-abu-lyahaba-upk/"),
    AcademyLecture(
        "MyQKhpRcrhw",
        "Урок 24: «аль-Масад», 2-3 аяты: «Он будет в Аду и не поможет ему, ни богатство, ни его дети» (УПК)",
        "meaning",
        1721,
        "https://abu-yasin.com/video/urok-24-al-masad-2-3-ayaty-on-budet-v-adu-i-ne-pomozhet-emu-/"),
    AcademyLecture(
        "KuXVScVtMX4",
        "Урок 25: «аль-Масад», 4-5 аяты: «Жена Абу Ляхаба будет в Аду вместе с своим мужем» (УПК)",
        "meaning",
        1987,
        "https://abu-yasin.com/video/urok-25-al-masad-4-5-ayaty-zhena-abu-lyahaba-budet-v-adu-vme/"),
    AcademyLecture(
        "y_Gt5jZMEhw",
        "Урок 26: «аль-Масад» Экзамен (УПК) / Проверь себя по сурам 111-114 + Фатиха",
        "meaning",
        673,
        "https://abu-yasin.com/video/urok-26-al-masad-ekzamen-upk-prover-sebya-po-suram-111-114-f/"),
    AcademyLecture(
        "lqrwJ7sosXk",
        "Урок 27: «ан-Наср», 1-ый аят: «Когда придёт помощь Аллаха и победа» (УПК)",
        "meaning",
        1667,
        "https://abu-yasin.com/video/urok-27-an-nasr-1-yy-ayat-kogda-pridet-pomosch-allaha-i-pobe/"),
    AcademyLecture(
        "jBs5_YwBVLs",
        "Урок 28: «ан-Наср», 2-ой аят: «Когда люди войдут в Ислам толпами» (УПК)",
        "meaning",
        2052,
        "https://abu-yasin.com/video/urok-28-an-nasr-2-oy-ayat-kogda-lyudi-voydut-v-islam-tolpami/"),
    AcademyLecture(
        "4UmJ_goa6gg",
        "Урок 29: «ан-Наср», 3-й аят: «Восхваляй Господа твоего и проси прощения» (УПК)",
        "meaning",
        2152,
        "https://abu-yasin.com/video/urok-29-an-nasr-3-y-ayat-voshvalyay-gospoda-tvoego-i-prosi-p/"),
    AcademyLecture(
        "ZfNkkxiwCFY",
        "Урок 30: «ан-Наср», Экзамен (УПК)",
        "meaning",
        750,
        "https://abu-yasin.com/video/urok-30-an-nasr-ekzamen-upk/"),
    AcademyLecture(
        "DxxTh9y0CxM",
        "Урок 31: «аль-Кяфирун», 1-3 аяты: «О неверные! Я не поклоняюсь тому чему поклоняетесь вы» (УПК)",
        "meaning",
        1940,
        "https://abu-yasin.com/video/urok-31-al-kyafirun-1-3-ayaty-o-nevernye-ya-ne-poklonyayus-t/"),
    AcademyLecture(
        "TVZGE2SagKE",
        "Урок 32: «аль-Кяфирун», 4-6 аяты: «У вас ваша религия, у меня моя Религия!» (УПК)",
        "meaning",
        2006,
        "https://abu-yasin.com/video/urok-32-al-kyafirun-4-6-ayaty-u-vas-vasha-religiya-u-menya-m/"),
    AcademyLecture(
        "vOkNqe0Yrqs",
        "Урок 33: «аль-Кафирун», Экзамен (УПК)",
        "meaning",
        967,
        "https://abu-yasin.com/video/urok-33-al-kafirun-ekzamen-upk/"),
    AcademyLecture(
        "PeWlfvzhRWc",
        "Урок 34: «аль-Кяусар», 1-2 аяты: «Мы даровали тебе изобильный источник Каусар» (УПК)",
        "meaning",
        2310,
        "https://abu-yasin.com/video/urok-34-al-kyausar-1-2-ayaty-my-darovali-tebe-izobilnyy-isto/"),
    AcademyLecture(
        "An0kleyjDMg",
        "Урок 35: «аль-Кяусар», 3 аят: «Враги твои будут унижены и всеми забыты» (УПК)",
        "meaning",
        1154,
        "https://abu-yasin.com/video/urok-35-al-kyausar-3-ayat-vragi-tvoi-budut-unizheny-i-vsemi-/"),
    AcademyLecture(
        "r5QFNLGrK7A",
        "Урок 36: «аль-Каусар», Экзамен (УПК)",
        "meaning",
        719,
        "https://abu-yasin.com/video/urok-36-al-kausar-ekzamen-upk/"),
    AcademyLecture(
        "FzCUUH5jlQ8",
        "Урок 37: «аль-Маун», 1-2 аяты: «Он не верит в Судный День и притесняет сироту» (УПК)",
        "meaning",
        2041,
        "https://abu-yasin.com/video/urok-37-al-maun-1-2-ayaty-on-ne-verit-v-sudnyy-den-i-pritesn/"),
    AcademyLecture(
        "CSyffMes92Q",
        "Урок 38: «аль-Маун», 3-4 аяты: «Он не кормит бедняка, и скверная у него молитва» (УПК)",
        "meaning",
        2065,
        "https://abu-yasin.com/video/urok-38-al-maun-3-4-ayaty-on-ne-kormit-bednyaka-i-skvernaya-/"),
    AcademyLecture(
        "ZgaQAzQxovo",
        "Урок 39 «аль-Маун», 5-6 аяты «Показушники небрежные к своему намазу»  (УПК)",
        "meaning",
        1982,
        "https://abu-yasin.com/video/urok-39-al-maun-5-6-ayaty-pokazushniki-nebrezhnye-k-svoemu-n/"),
    AcademyLecture(
        "ug5ttwrPiDg",
        "Урок 40 «аль-Маун», 7 аят «… они не делятся даже самым малым» (УПК)",
        "meaning",
        892,
        "https://abu-yasin.com/video/urok-40-al-maun-7-ayat-oni-ne-delyatsya-dazhe-samym-malym-up/"),
    AcademyLecture(
        "yxeEU7dULCo",
        "Урок 41 «аль-Маун», Повторение арабского  (УПК)",
        "meaning",
        1502,
        "https://abu-yasin.com/video/urok-41-al-maun-povtorenie-arabskogo-upk/"),
    AcademyLecture(
        "GfPzSV1nSms",
        "Урок 42 «аль-Маун», Экзамен  (УПК)",
        "meaning",
        1152,
        "https://abu-yasin.com/video/urok-42-al-maun-ekzamen-upk/"),
    AcademyLecture(
        "M8VbIgB4vBQ",
        "Урок 43: Три части речи. Элементы арабского  (УПК)",
        "meaning",
        2118,
        "https://abu-yasin.com/video/urok-43-tri-chasti-rechi-elementy-arabskogo-upk/"),
    AcademyLecture(
        "BhyG5s2QA8M",
        "Урок 44 «Курайш», 1-2 аяты «Кто такие Курайшиты?» (УПК)",
        "meaning",
        2703,
        "https://abu-yasin.com/video/urok-44-kuraysh-1-2-ayaty-kto-takie-kurayshity-upk/"),
    AcademyLecture(
        "gwcFQAV7KeA",
        "Урок 45 «Курайш», 3-4 аяты «Пусть поклоняются только Господу Каабы» (УПК)",
        "meaning",
        2594,
        "https://abu-yasin.com/video/urok-45-kuraysh-3-4-ayaty-pust-poklonyayutsya-tolko-gospodu-/"),
    AcademyLecture(
        "w_6Mg8fWtqM",
        "Урок 46: сура «Курайш», Экзамен  (УПК)",
        "meaning",
        1029,
        "https://abu-yasin.com/video/urok-46-sura-kuraysh-ekzamen-upk/"),
    AcademyLecture(
        "KG8gTsejHx0",
        "Урок 47 «аль-Филь», 1 аят «… Разве ты не знаешь , как поступил Аллах с воинством слона?!» (УПК)",
        "meaning",
        2333,
        "https://abu-yasin.com/video/urok-47-al-fil-1-ayat-razve-ty-ne-znaesh-kak-postupil-allah-/"),
    AcademyLecture(
        "Aay1RDDFowQ",
        "Урок 48 «аль-Филь»,  аяты 2-3 «… Разве Аллах не обратил их планы в убыток?!» (УПК)",
        "meaning",
        2136,
        "https://abu-yasin.com/video/urok-48-al-fil-ayaty-2-3-razve-allah-ne-obratil-ih-plany-v-u/"),
    AcademyLecture(
        "bBgPhq1888g",
        "Урок 49: «аль-Филь»,  аяты 4-5 «Они все сгнили, как изъеденные листья» (УПК)",
        "meaning",
        1772,
        "https://abu-yasin.com/video/urok-49-al-fil-ayaty-4-5-oni-vse-sgnili-kak-izedennye-listya/"),
    AcademyLecture(
        "7iP3V6I3ARg",
        "Урок 50: «аль-Филь»,  Экзамен (УПК)",
        "meaning",
        851,
        "https://abu-yasin.com/video/urok-50-al-fil-ekzamen-upk/"),
    AcademyLecture(
        "YCkTTWKYtcQ",
        "Урок 51: «Именные падежи» Элементы арабского в пройденных сурах (УПК)",
        "meaning",
        1896,
        "https://abu-yasin.com/video/urok-51-imennye-padezhi-elementy-arabskogo-v-proydennyh-sura/"),
    AcademyLecture(
        "RO0otabrDnQ",
        "1) Азан ( фразы, произношение, смысл)",
        "prayer",
        988,
        "https://abu-yasin.com/video/1-azan-frazy-proiznoshenie-smysl/"),
    AcademyLecture("EpJzSrLj49Y", "2) Ошибки при произнесении Азана", "prayer",
        827, "https://abu-yasin.com/video/2-oshibki-pri-proiznesenii-azana/"),
    AcademyLecture("MbzHf1tryWQ", "3) Икама. Исправление ошибок.", "prayer",
        768, "https://abu-yasin.com/video/3-ikama-ispravlenie-oshibok/"),
    AcademyLecture(
        "aXfWCZ-m1qU",
        "4) Что говорить, когда слышишь азан?",
        "prayer",
        482,
        "https://abu-yasin.com/video/4-chto-govorit-kogda-slyshish-azan/"),
    AcademyLecture("jTG2RQxIdhs", "5) Салават после Азана", "prayer", 247,
        "https://abu-yasin.com/video/5-salavat-posle-azana/"),
    AcademyLecture(
        "2HvIKuFJjzI",
        "6) Молитва «аль-Василя» после Азана",
        "prayer",
        583,
        "https://abu-yasin.com/video/6-molitva-al-vasilya-posle-azana/"),
    AcademyLecture("sqc7H5cmZmA", "7) «Шахада» после Азана", "prayer", 736,
        "https://abu-yasin.com/video/7-shahada-posle-azana/"),
    AcademyLecture("aMCSy_-sN9Y", "8) Дуа после тахарата (1-ое)", "prayer", 586,
        "https://abu-yasin.com/video/8-dua-posle-taharata-1-oe/"),
    AcademyLecture("kumK5dTm73k", "9) Дуа после тахарата (2-ое)", "prayer", 477,
        "https://abu-yasin.com/video/9-dua-posle-taharata-2-oe/"),
    AcademyLecture("dePf8Dmg42s", "10) Такбират-уль-Ихрам", "prayer", 497,
        "https://abu-yasin.com/video/10-takbirat-ul-ihram/"),
    AcademyLecture("stCOgTU6AJM", "11) Дуа Истифтах (Субханака)", "prayer", 268,
        "https://abu-yasin.com/video/11-dua-istiftah-subhanaka/"),
    AcademyLecture("KWV6C_v7TlY", "12) Истиаза и Басмаля", "prayer", 550,
        "https://abu-yasin.com/video/12-istiaza-i-basmalya/"),
    AcademyLecture("hsZc0WM8KvI", "13) Сура «аль-Фатиха» (الفَاتِحَة)",
        "prayer", 1441, "https://abu-yasin.com/video/13-sura-al-fatiha/"),
    AcademyLecture("NLQE2UbPbuk", "14) Сура аль-Ихлас", "prayer", 847,
        "https://abu-yasin.com/video/14-sura-al-ihlas/"),
    AcademyLecture(
        "QEJqXvDi0Vk",
        "15) Слова произносимые в поясном поклоне (Руку’)",
        "prayer",
        376,
        "https://abu-yasin.com/video/15-slova-proiznosimye-v-poyasnom-poklone-ruku/"),
    AcademyLecture(
        "U9Um4jDQcaA",
        "16) Подъём из Руку’  (из поясного поклона) ч.1",
        "prayer",
        313,
        "https://abu-yasin.com/video/16-podem-iz-ruku-iz-poyasnogo-poklona-ch-1/"),
    AcademyLecture(
        "Jqibu7DWuso",
        "17) После подъёма из Руку’ (из поясного поклона)",
        "prayer",
        472,
        "https://abu-yasin.com/video/17-posle-podema-iz-ruku-iz-poyasnogo-poklona/"),
    AcademyLecture("EmA1IoCfTZs", "18) Дуа в Суджуде", "prayer", 549,
        "https://abu-yasin.com/video/18-dua-v-sudzhude/"),
    AcademyLecture("6Sg2JCBecW8", "19) Дуа между суджудами", "prayer", 507,
        "https://abu-yasin.com/video/19-dua-mezhdu-sudzhudami/"),
    AcademyLecture("Hhe6yGFUVVE", "20) Тахийят  - Ташаххуд", "prayer", 957,
        "https://abu-yasin.com/video/20-tahiyyat-tashahhud/"),
    AcademyLecture("VsO4JZCuNvM", "21) Салават", "prayer", 647,
        "https://abu-yasin.com/video/21-salavat/"),
    AcademyLecture("k4Ur6dgDjak", "22) Дуа перед салямом (№ 1).", "prayer", 989,
        "https://abu-yasin.com/video/22-dua-pered-salyamom-1/"),
    AcademyLecture("0cEoq25NJBA", "23) Дуа перед Салямом (№ 2)", "prayer", 406,
        "https://abu-yasin.com/video/23-dua-pered-salyamom-2/"),
    AcademyLecture("DzhWktpN2rE", "24) Зикр после намаза (№ 1)", "prayer", 518,
        "https://abu-yasin.com/video/24-zikr-posle-namaza-1/"),
    AcademyLecture(
        "cUP8nn9gCNM",
        "25) Зикр после намаза (№ 2) «Аят аль-Курси»",
        "prayer",
        1523,
        "https://abu-yasin.com/video/25-zikr-posle-namaza-2-ayat-al-kursi/"),
    AcademyLecture(
        "Eh7ss-OucOs",
        "26) Зикр после намаза (№ 3) ТАСБИХ 3/33",
        "prayer",
        1194,
        "https://abu-yasin.com/video/26-zikr-posle-namaza-3-tasbih-3-33/"),
    AcademyLecture(
        "47t9FoyhVZg",
        "27) Зикр после намаза (№ 4) «Ля щарика ляh»",
        "prayer",
        604,
        "https://abu-yasin.com/video/27-zikr-posle-namaza-4-lya-scharika-lyah/"),
    AcademyLecture(
        "2W7retN9Jac",
        "28) Зикр после намаза (№ 5)  «Ля мани’а ли-ма а’тайта»",
        "prayer",
        550,
        "https://abu-yasin.com/video/28-zikr-posle-namaza-5-lya-mani-a-li-ma-a-tayta/"),
    AcademyLecture(
        "BygYWY56gGo",
        "29) Дуа кунут № 1. Молитва произносимая в последнем ракаате  витр-намаза",
        "prayer",
        1156,
        "https://abu-yasin.com/video/29-dua-kunut-1-molitva-proiznosimaya-v-poslednem-rakaate-vit/"),
    AcademyLecture("dWS5qSWqVms", "30) Дуа кунут № 2", "prayer", 573,
        "https://abu-yasin.com/video/30-dua-kunut-2/"),
  ];

  static AcademyLecture? byYoutubeId(String id) {
    for (final lecture in all) {
      if (lecture.youtubeId == id) return lecture;
    }
    return null;
  }
}
