import '../../models/lesson.dart';

final List<Lesson> arabicLessons = [
    const Lesson(
      id: 'a1',
      title: 'Первые буквы',
      subtitle: 'Алиф, Ба, Та: звук, форма и голос',
      course: CourseType.arabic,
      order: 1,
      status: LessonStatus.available,
      xpReward: 20,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'ا  ب  ت',
          transliteration: 'Алиф, Ба, Та',
          russianText: 'Начинаем с трёх базовых букв. Сначала узнай форму, '
              'потом выбери правильный ответ и произнеси звук.',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'ا',
          transliteration: 'Алиф',
          russianText: 'Алиф часто передаёт долгий звук «а».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'У какой из этих букв совсем нет точек?',
          answers: ['ب', 'ت', 'ا'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'ب',
          transliteration: 'Ба',
          russianText: 'Произнеси букву Ба.',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Две точки сверху — это признак какой буквы?',
          answers: ['ا', 'ت', 'ب'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Одна точка снизу отличает букву...',
          answers: ['ت', 'ب', 'ا'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какой звук часто передаёт Алиф?',
          answers: ['«т»', 'Долгий «а»', '«б»'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'ا', answer: 'Алиф'),
            LessonMatchPair(prompt: 'ب', answer: 'Ба'),
            LessonMatchPair(prompt: 'ت', answer: 'Та'),
          ],
        ),
      ],
    ),
    const Lesson(
      id: 'a2',
      title: 'Короткие гласные',
      subtitle: 'Фатха, касра и дамма',
      course: CourseType.arabic,
      order: 2,
      xpReward: 20,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'بَ  بِ  بُ',
          transliteration: 'ба, би, бу',
          russianText: 'Фатха даёт звук «а», касра — «и», дамма — «у».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Если под буквой стоит касра, какой звук добавляется?',
          answers: ['а', 'и', 'у'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини знак и звук',
          russianText: 'Здесь нужно вспомнить не слово целиком, а роль огласовки.',
          matchPairs: [
            LessonMatchPair(prompt: 'بَ', answer: 'ба'),
            LessonMatchPair(prompt: 'بِ', answer: 'би'),
            LessonMatchPair(prompt: 'بُ', answer: 'бу'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'بَ بِ بُ',
          transliteration: 'ба би бу',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Огласовка стоит НАД буквой и даёт «у». Это...',
          answers: ['фатха', 'дамма', 'касра'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Чем «بَ» отличается от «بِ»?',
          answers: ['Только огласовкой (а/и)', 'Самой буквой', 'Ничем'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Слог «بُ» — как он читается?',
          answers: ['ба', 'би', 'бу'],
          correctAnswerIndex: 2,
        ),
      ],
    ),
    const Lesson(
      id: 'a3',
      title: 'Собери слог',
      subtitle: 'Чтение простых сочетаний',
      course: CourseType.arabic,
      order: 3,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'تَ  بَ  بَا',
          transliteration: 'та, ба, баа',
          russianText: 'Теперь соединяем буквы и гласные в короткие слоги.',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какой вариант отличается от «بَ» только буквой, а не гласной?',
          answers: ['تَ', 'بَا', 'بُ'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'تَ',
          transliteration: 'та',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'В каком слоге есть долгая гласная?',
          answers: ['بَ', 'بَا', 'تَ'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Слог «تَ» — как он читается?',
          answers: ['ба', 'та', 'баа'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Слоги «بَ» и «تَ» отличаются друг от друга...',
          answers: ['гласной', 'буквой', 'длиной звука'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини слог и его звучание',
          matchPairs: [
            LessonMatchPair(prompt: 'تَ', answer: 'та'),
            LessonMatchPair(prompt: 'بَ', answer: 'ба'),
            LessonMatchPair(prompt: 'بَا', answer: 'баа'),
          ],
        ),
      ],
    ),
    const Lesson(
      id: 'a4',
      title: 'Ещё буквы',
      subtitle: 'Мим, Нун, Лям: форма и звук',
      course: CourseType.arabic,
      order: 4,
      xpReward: 20,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'م  ن  ل',
          transliteration: 'Мим, Нун, Лям',
          russianText: 'Продолжаем изучать буквы. Узнай форму, выбери правильный '
              'ответ и произнеси звук.',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'م',
          transliteration: 'Мим',
          russianText: 'Буква Мим передаёт звук «м».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая из этих букв читается как «н»?',
          answers: ['م', 'ن', 'ل'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и звук',
          matchPairs: [
            LessonMatchPair(prompt: 'م', answer: 'м'),
            LessonMatchPair(prompt: 'ن', answer: 'н'),
            LessonMatchPair(prompt: 'ل', answer: 'л'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'ل',
          transliteration: 'Лям',
          russianText: 'Произнеси букву Лям.',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Буква «ل» называется...',
          answers: ['Мим', 'Лям', 'Нун'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Звук «м» даёт буква...',
          answers: ['ن', 'م', 'ل'],
          correctAnswerIndex: 1,
        ),
      ],
    ),
    const Lesson(
      id: 'a5',
      title: 'Долгие гласные',
      subtitle: 'Алиф, Вав и Йа удлиняют звук',
      course: CourseType.arabic,
      order: 5,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'بَا  بُو  بِي',
          transliteration: 'баа, буу, бии',
          russianText: 'Буквы ا, و, ي после огласовки удлиняют гласный: получается '
              'долгое «а», «у», «и».',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'بَا',
          transliteration: 'баа',
          russianText: 'После фатхи алиф даёт долгий звук «а».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какое сочетание даёт долгий звук «и»?',
          answers: ['بَا', 'بُو', 'بِي'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини слог и звук',
          matchPairs: [
            LessonMatchPair(prompt: 'بَا', answer: 'баа'),
            LessonMatchPair(prompt: 'بُو', answer: 'буу'),
            LessonMatchPair(prompt: 'بِي', answer: 'бии'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'بُو',
          transliteration: 'буу',
          russianText: 'Произнеси долгий слог «буу».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Долгий звук «у» получается с помощью буквы...',
          answers: ['ا', 'و', 'ي'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Что общего у слогов بَا, بُو и بِي?',
          answers: ['Все с долгой гласной', 'Все закрыты сукуном', 'Во всех буква ن'],
          correctAnswerIndex: 0,
        ),
      ],
    ),
    const Lesson(
      id: 'a6',
      title: 'Сукун и слог',
      subtitle: 'Закрытый слог без гласной',
      course: CourseType.arabic,
      order: 6,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'تَبْ  بَتْ',
          transliteration: 'таб, бат',
          russianText: 'Сукун (ـْ) означает, что у буквы нет своей гласной: она '
              'закрывает слог. تَبْ читается «таб».',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'بْ',
          transliteration: 'б (без гласной)',
          russianText: 'Сукун показывает остановку голоса без добавления гласной.',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Что означает знак сукун (ـْ)?',
          answers: ['Долгую гласную', 'Отсутствие гласной у буквы', 'Удвоение буквы'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'تَبْ',
          transliteration: 'таб',
          russianText: 'Произнеси закрытый слог «таб».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Слог «بَتْ» читается как...',
          answers: ['таб', 'бат', 'баа'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Чем «تَبْ» отличается от «بَتْ»?',
          answers: ['Порядком букв', 'Гласными звуками', 'Ничем'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини слог и его звучание',
          matchPairs: [
            LessonMatchPair(prompt: 'تَبْ', answer: 'таб'),
            LessonMatchPair(prompt: 'بَتْ', answer: 'бат'),
            LessonMatchPair(prompt: 'بَا', answer: 'баа'),
          ],
        ),
      ],
    ),
    const Lesson(
      id: 'a7',
      title: 'Са, Джим, Ха, Ха',
      subtitle: 'Буквы ث ج ح خ',
      course: CourseType.arabic,
      order: 7,
      xpReward: 20,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'ث  ج  ح  خ',
          transliteration: 'Са, Джим, Ха, Ха',
          russianText: 'Четыре новые буквы. ث даёт межзубный «с», ج — «дж», '
              'ح — глубокий гортанный «х», خ — хриплый «х».',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'ج',
          transliteration: 'Джим',
          russianText: 'Буква Джим передаёт звук «дж».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая из этих букв читается как «дж»?',
          answers: ['ث', 'ج', 'خ'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'У какой из этих букв три точки сверху?',
          answers: ['ث', 'ج', 'ح'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Похожие по форме ح и خ различаются...',
          answers: ['Точкой сверху у خ', 'Ничем', 'Точкой снизу у ح'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Буква «ث» называется...',
          answers: ['Джим', 'Са (тха)', 'Ха'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'ث', answer: 'Са (тха)'),
            LessonMatchPair(prompt: 'ج', answer: 'Джим'),
            LessonMatchPair(prompt: 'ح', answer: 'Ха (ح)'),
            LessonMatchPair(prompt: 'خ', answer: 'Ха (خ)'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'خَ',
          transliteration: 'ха',
          russianText: 'Произнеси слог с буквой Ха (خ) — хриплый «х».',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a8',
      title: 'Даль, Заль, Ра, Зай',
      subtitle: 'Буквы د ذ ر ز',
      course: CourseType.arabic,
      order: 8,
      xpReward: 20,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'د  ذ  ر  ز',
          transliteration: 'Даль, Заль, Ра, Зай',
          russianText: 'Эти буквы не соединяются со следующей. د — «д», '
              'ذ — межзубный «з», ر — «р», ز — «з».',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'ر',
          transliteration: 'Ра',
          russianText: 'Буква Ра передаёт раскатистый звук «р».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква читается как «р»?',
          answers: ['د', 'ز', 'ر'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Чем «ذ» отличается от «د»?',
          answers: ['Точкой сверху', 'Ничем', 'Точкой снизу'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая из этих букв — Зай (звук «з»)?',
          answers: ['ر', 'ز', 'د'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Буква «د» называется...',
          answers: ['Даль', 'Зай', 'Ра'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'د', answer: 'Даль'),
            LessonMatchPair(prompt: 'ذ', answer: 'Заль'),
            LessonMatchPair(prompt: 'ر', answer: 'Ра'),
            LessonMatchPair(prompt: 'ز', answer: 'Зай'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'رَ',
          transliteration: 'ра',
          russianText: 'Произнеси слог с буквой Ра.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a9',
      title: 'Син, Шин, Сад, Дад',
      subtitle: 'Буквы س ش ص ض',
      course: CourseType.arabic,
      order: 9,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'س  ش  ص  ض',
          transliteration: 'Син, Шин, Сад, Дад',
          russianText: 'س — «с», ش — «ш». ص и ض — эмфатические (твёрдые) «с» и «д», '
              'произносятся с напряжением языка.',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'ش',
          transliteration: 'Шин',
          russianText: 'Буква Шин передаёт звук «ш».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква читается как «ш»?',
          answers: ['س', 'ش', 'ص'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Чем отличается «ش» от «س»?',
          answers: ['Тремя точками сверху', 'Хвостиком снизу', 'Ничем'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква даёт эмфатический (твёрдый) «с»?',
          answers: ['ش', 'ض', 'ص'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Буквы ص и ض отличаются от س и других тем, что они...',
          answers: ['Эмфатические (твёрдые)', 'Гласные', 'Мягче обычных'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'س', answer: 'Син'),
            LessonMatchPair(prompt: 'ش', answer: 'Шин'),
            LessonMatchPair(prompt: 'ص', answer: 'Сад'),
            LessonMatchPair(prompt: 'ض', answer: 'Дад'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'صَ',
          transliteration: 'са',
          russianText: 'Произнеси слог с эмфатической буквой Сад.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a10',
      title: 'Та, За, Айн, Гайн',
      subtitle: 'Буквы ط ظ ع غ',
      course: CourseType.arabic,
      order: 10,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'ط  ظ  ع  غ',
          transliteration: 'Та, За, Айн, Гайн',
          russianText: 'ط и ظ — эмфатические «т» и «з». ع — гортанный звук «айн», '
              'غ — картавый «г», похожий на французское «r».',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'ع',
          transliteration: 'Айн',
          russianText: 'Буква Айн — глубокий гортанный звук, его нет в русском.',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква обозначает гортанный звук «айн»?',
          answers: ['ط', 'ع', 'غ'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Чем отличается «غ» от «ع»?',
          answers: ['Точкой сверху', 'Ничем', 'Точкой снизу'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Буква «ط» называется...',
          answers: ['Айн', 'Гайн', 'Та (эмфатическая)'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая пара — это эмфатические (твёрдые) буквы?',
          answers: ['ط и ظ', 'ع и غ', 'ط и ع'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'ط', answer: 'Та (ط)'),
            LessonMatchPair(prompt: 'ظ', answer: 'За (ظ)'),
            LessonMatchPair(prompt: 'ع', answer: 'Айн'),
            LessonMatchPair(prompt: 'غ', answer: 'Гайн'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'عَ',
          transliteration: 'а (айн)',
          russianText: 'Произнеси слог с буквой Айн.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a11',
      title: 'Фа, Каф, Кяф',
      subtitle: 'Буквы ف ق ك',
      course: CourseType.arabic,
      order: 11,
      xpReward: 20,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'ف  ق  ك',
          transliteration: 'Фа, Каф, Кяф',
          russianText: 'ف — «ф», ق — глубокий «къ» из глубины горла, '
              'ك — обычный «к».',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'ق',
          transliteration: 'Каф',
          russianText: 'Буква Каф — глубокий «къ», произносится дальше во рту, чем «ك».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква даёт глубокий «къ»?',
          answers: ['ف', 'ق', 'ك'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Чем ق отличается от ك по произношению?',
          answers: ['Произносится глубже в горле', 'Ничем', 'Звучит мягче'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'У какой из этих букв две точки сверху?',
          answers: ['ف', 'ق', 'ك'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Буква «ف» называется...',
          answers: ['Фа', 'Каф', 'Кяф'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'ف', answer: 'Фа'),
            LessonMatchPair(prompt: 'ق', answer: 'Каф'),
            LessonMatchPair(prompt: 'ك', answer: 'Кяф'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'قَ',
          transliteration: 'къа',
          russianText: 'Произнеси слог с буквой Каф.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a12',
      title: 'Ха, Вав, Йа',
      subtitle: 'Буквы ه و ي как согласные',
      course: CourseType.arabic,
      order: 12,
      xpReward: 20,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'ه  و  ي',
          transliteration: 'Ха, Вав, Йа',
          russianText: 'ه — лёгкий выдох «х». و и ي как согласные дают «в» и «й» '
              '(а как долгие гласные — «у» и «и»).',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'و',
          transliteration: 'Вав',
          russianText: 'Как согласная буква Вав передаёт звук «в».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какой звук даёт «ي» как согласная?',
          answers: ['«в»', 'лёгкий «х»', '«й»'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какой звук даёт «و» как согласная?',
          answers: ['«й»', 'лёгкий «х»', '«в»'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Особенность букв و и ي в том, что они могут быть...',
          answers: ['И согласными, и долгими гласными', 'Только гласными', 'Только огласовками'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Буква «ه» называется...',
          answers: ['Ха (ه)', 'Вав', 'Йа'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'ه', answer: 'Ха (ه)'),
            LessonMatchPair(prompt: 'و', answer: 'Вав'),
            LessonMatchPair(prompt: 'ي', answer: 'Йа'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'وَ',
          transliteration: 'ва',
          russianText: 'Произнеси слог с буквой Вав как согласной.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a13',
      title: 'Танвин',
      subtitle: 'Окончания -ан, -ин, -ун',
      course: CourseType.arabic,
      order: 13,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'بً  بٍ  بٌ',
          transliteration: 'бан, бин, бун',
          russianText: 'Танвин — двойная огласовка. Она добавляет носовой «н» в конце: '
              'фатхатан (ً) — «-ан», касратан (ٍ) — «-ин», даммататан (ٌ) — «-ун».',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'بً',
          transliteration: 'бан',
          russianText: 'Двойная фатха над буквой читается как «-ан».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какое окончание даёт танвин с касрой (ٍ)?',
          answers: ['-ан', '-ин', '-ун'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Что добавляет танвин к звуку буквы?',
          answers: ['Долготу гласной', 'Удвоение буквы', 'Носовой «н» в конце'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Слог «بٌ» читается как...',
          answers: ['бун', 'бан', 'бин'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини знак и звук',
          matchPairs: [
            LessonMatchPair(prompt: 'بً', answer: 'бан'),
            LessonMatchPair(prompt: 'بٍ', answer: 'бин'),
            LessonMatchPair(prompt: 'بٌ', answer: 'бун'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'بً بٍ بٌ',
          transliteration: 'бан бин бун',
          russianText: 'Произнеси три окончания с танвином.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a14',
      title: 'Шадда',
      subtitle: 'Удвоение буквы',
      course: CourseType.arabic,
      order: 14,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'بَّ  بَبْ',
          transliteration: 'бб (аб-ба)',
          russianText: 'Шадда (ـّ) означает удвоение буквы: буква произносится дважды, '
              'с лёгкой задержкой. Это как сукун на первой букве плюс гласная на второй.',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'بَّ',
          transliteration: 'бба',
          russianText: 'Шадда над буквой удваивает её звук.',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Что означает знак шадда (ـّ)?',
          answers: ['Удвоение буквы', 'Отсутствие гласной', 'Носовой «н»'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Как правильно прочитать удвоенную букву?',
          answers: ['Короче обычной', 'С задержкой, как две буквы', 'Пропустить её'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'По сути шадда — это как...',
          answers: [
            'Сукун на букве плюс гласная на ней же',
            'Долгая гласная',
            'Танвин в конце слова',
          ],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини знак и его роль',
          matchPairs: [
            LessonMatchPair(prompt: 'ـّ', answer: 'удвоение'),
            LessonMatchPair(prompt: 'ـْ', answer: 'без гласной'),
            LessonMatchPair(prompt: 'ـً', answer: 'окончание -ан'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'رَبَّ',
          transliteration: 'рабба',
          russianText: 'Произнеси удвоенную букву в слоге «рабба».',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a15',
      title: 'Мадд — долгота',
      subtitle: 'Удлинение через ا و ي',
      course: CourseType.arabic,
      order: 15,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'بَا  بُو  بِي',
          transliteration: 'баа, буу, бии',
          russianText: 'Мадд — это долгота гласной. Буква ا удлиняет «а», و — «у», '
              'ي — «и». Долгий звук тянется примерно вдвое дольше короткого.',
        ),
        LessonStep(
          type: LessonStepType.audio,
          arabicText: 'بِي',
          transliteration: 'бии',
          russianText: 'После касры буква ي даёт долгий звук «и».',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква удлиняет звук «у»?',
          answers: ['ا', 'و', 'ي'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква удлиняет звук «а»?',
          answers: ['و', 'ي', 'ا'],
          correctAnswerIndex: 2,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Насколько долгий звук длиннее короткого?',
          answers: ['Примерно вдвое', 'Не отличается', 'Втрое короче'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву долготы и звук',
          matchPairs: [
            LessonMatchPair(prompt: 'ا', answer: 'долгий «а»'),
            LessonMatchPair(prompt: 'و', answer: 'долгий «у»'),
            LessonMatchPair(prompt: 'ي', answer: 'долгий «и»'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'بِي',
          transliteration: 'бии',
          russianText: 'Произнеси долгий слог «бии», протягивая звук.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
    const Lesson(
      id: 'a16',
      title: 'Чтение: весь алфавит',
      subtitle: 'Практика и повторение',
      course: CourseType.arabic,
      order: 16,
      xpReward: 25,
      steps: [
        LessonStep(
          type: LessonStepType.text,
          arabicText: 'ا ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي',
          transliteration: 'Полный алфавит',
          russianText: 'Ты изучил все 28 букв арабского алфавита и основные знаки '
              'огласовки. Повторим самое важное и попрактикуемся в чтении.',
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква даёт глубокий гортанный «айн»?',
          answers: ['غ', 'ع', 'ح'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Как читается «بٌ» (танвин с даммой)?',
          answers: ['бун', 'бан', 'бин'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какой из знаков удваивает букву?',
          answers: ['Сукун (ـْ)', 'Шадда (ـّ)', 'Танвин (ـً)'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'Какая буква обозначает эмфатический (твёрдый) «т»?',
          answers: ['ت', 'ط', 'د'],
          correctAnswerIndex: 1,
        ),
        LessonStep(
          type: LessonStepType.question,
          question: 'В каком порядке эти буквы идут в алфавите?',
          answers: ['ب ت ث', 'ت ب ث', 'ث ب ت'],
          correctAnswerIndex: 0,
        ),
        LessonStep(
          type: LessonStepType.matching,
          question: 'Соедини букву и её название',
          matchPairs: [
            LessonMatchPair(prompt: 'ج', answer: 'Джим'),
            LessonMatchPair(prompt: 'ق', answer: 'Каф'),
            LessonMatchPair(prompt: 'ش', answer: 'Шин'),
            LessonMatchPair(prompt: 'غ', answer: 'Гайн'),
          ],
        ),
        LessonStep(
          type: LessonStepType.speak,
          arabicText: 'قَرَأَ',
          transliteration: 'къараа',
          russianText: 'Прочитай слово «къараа» (читал), соединяя знакомые буквы.',
          speechMode: SpeechMode.arabic,
        ),
      ],
    ),
];
