import '../../models/lesson.dart';

final List<Lesson> quranShortSurahsB = [
  const Lesson(
    id: 'q_ala_1',
    title: 'Аль-Аля',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 28,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText: 'Аль-Аля означает «Всевышний». Сура велит славить имя '
            'Господа, напоминает о Его творении и наставлении, и учит, что '
            'преуспел тот, кто очистился, поминал Господа и молился.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5949,
        arabicText: 'سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَى',
        transliteration: "Саббихисма раббикаль-а'ля",
        russianText: 'Славь имя Господа твоего Всевышнего',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5950,
        arabicText: 'الَّذِى خَلَقَ فَسَوَّىٰ',
        transliteration: 'Аллязи халака фасавва',
        russianText: 'который сотворил всё сущее и придал ему соразмерность',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5951,
        arabicText: 'وَالَّذِى قَدَّرَ فَهَدَىٰ',
        transliteration: 'Валлязи каддара фахада',
        russianText: 'который предопределил и направил к цели',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5952,
        arabicText: 'وَالَّذِىٓ أَخْرَجَ الْمَرْعَىٰ',
        transliteration: "Валлязи ахраджаль-мар'а",
        russianText: 'который взрастил пастбище',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5953,
        arabicText: 'فَجَعَلَهُۥ غُثَآءً أَحْوَىٰ',
        transliteration: "Фаджа'аляху гусаан ахва",
        russianText: 'а потом превратил его в сухую бурую массу',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5954,
        arabicText: 'سَنُقْرِئُكَ فَلَا تَنسَىٰٓ',
        transliteration: "Санукри'ука фаля танса",
        russianText: 'Мы прочтём тебе, и ты не забудешь',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5955,
        arabicText:
            'إِلَّا مَا شَآءَ اللَّهُ ۚ إِنَّهُۥ يَعْلَمُ الْجَهْرَ وَمَا يَخْفَىٰ',
        transliteration: "Илля ма шаа-ллаху, иннаху я'лямуль-джахра ва ма яхфа",
        russianText: 'кроме того, что пожелает Аллах. Он знает явное и то, '
            'что сокрыто',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5956,
        arabicText: 'وَنُيَسِّرُكَ لِلْيُسْرَىٰ',
        transliteration: 'Ва нуяссирука лиль-юсра',
        russianText: 'Мы облегчим тебе путь к легчайшему',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5957,
        arabicText: 'فَذَكِّرْ إِن نَّفَعَتِ الذِّكْرَىٰ',
        transliteration: "Фазаккир ин нафа'атиз-зикра",
        russianText: 'Наставляй же, если наставление принесёт пользу',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5958,
        arabicText: 'سَيَذَّكَّرُ مَن يَخْشَىٰ',
        transliteration: 'Саяззаккару ман яхша',
        russianText: 'Воспримет его тот, кто боится Аллаха',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5959,
        arabicText: 'وَيَتَجَنَّبُهَا الْأَشْقَى',
        transliteration: 'Ва ятаджаннабухаль-ашка',
        russianText: 'и уклонится от него самый несчастный',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5960,
        arabicText: 'الَّذِى يَصْلَى النَّارَ الْكُبْرَىٰ',
        transliteration: 'Аллязи ясляан-нараль-кубра',
        russianText: 'который войдёт в Огонь величайший',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5961,
        arabicText: 'ثُمَّ لَا يَمُوتُ فِيهَا وَلَا يَحْيَىٰ',
        transliteration: 'Сумма ля ямуту фиха ва ля яхья',
        russianText: 'где не умрёт и не будет жить',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5962,
        arabicText: 'قَدْ أَفْلَحَ مَن تَزَكَّىٰ',
        transliteration: 'Кад афляха ман тазакка',
        russianText: 'Преуспел тот, кто очистился',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5963,
        arabicText: 'وَذَكَرَ اسْمَ رَبِّهِۦ فَصَلَّىٰ',
        transliteration: 'Ва закарасма раббихи фасалля',
        russianText: 'поминал имя Господа своего и совершал молитву',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5964,
        arabicText: 'بَلْ تُؤْثِرُونَ الْحَيَوٰةَ الدُّنْيَا',
        transliteration: "Баль ту'сируналь-хаятад-дунья",
        russianText: 'Но вы отдаёте предпочтение мирской жизни',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5965,
        arabicText: 'وَالْـَٔاخِرَةُ خَيْرٌۭ وَأَبْقَىٰٓ',
        transliteration: 'Валь-ахырату хайрун ва абка',
        russianText: 'хотя Последняя жизнь лучше и вечнее',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5966,
        arabicText: 'إِنَّ هَٰذَا لَفِى الصُّحُفِ الْأُولَىٰ',
        transliteration: 'Инна хаза ляфис-сухуфиль-уля',
        russianText: 'Воистину, это записано в первых свитках',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5967,
        arabicText: 'صُحُفِ إِبْرَٰهِيمَ وَمُوسَىٰ',
        transliteration: 'Сухуфи ибрахима ва муса',
        russianText: 'свитках Ибрахима (Авраама) и Мусы (Моисея)',
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'С чего начинается сура Аль-Аля?',
        answers: [
          'Со славословия имени Господа Всевышнего',
          'С клятвы смоковницей и оливой',
          'С клятвы предвечерним временем'
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Кто, по суре Аль-Аля, преуспел?',
        answers: [
          'Тот, кто накопил больше всех',
          'Тот, кто очистился, поминал Господа и молился',
          'Тот, кто предпочёл мирскую жизнь'
        ],
        correctAnswerIndex: 1,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Какая жизнь, по суре, лучше и вечнее?',
        answers: ['Мирская жизнь', 'Жизнь в богатстве', 'Последняя жизнь'],
        correctAnswerIndex: 2,
      ),
      // Cloze на арабском: чем завершается «Преуспел тот, кто…».
      LessonStep(
        type: LessonStepType.question,
        question:
            'Заполни пропуск: «قَدْ أَفْلَحَ مَن ___» (преуспел тот, кто…)',
        answers: ['تَزَكَّىٰ', 'جَمَعَ', 'كَذَّبَ'],
        correctAnswerIndex: 0,
      ),
      // Логика: кому противопоставлен преуспевший.
      LessonStep(
        type: LessonStepType.question,
        question:
            'Кому в конце суры противопоставлен тот, кто очистился и молился?',
        answers: [
          'Тем, кто предпочёл мирскую жизнь, хотя Последняя лучше и вечнее',
          'Тем, кто клялся смоковницей и оливой',
          'Владельцам слона'
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Сопоставь слова с их смыслом',
        matchPairs: [
          LessonMatchPair(prompt: 'الْأَعْلَى', answer: 'Всевышний'),
          LessonMatchPair(prompt: 'خَلَقَ', answer: 'Сотворил'),
          LessonMatchPair(prompt: 'الْـَٔاخِرَةُ', answer: 'Последняя жизнь'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5949,
        arabicText: 'سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَى',
        transliteration: "Саббихисма раббикаль-а'ля",
        russianText: 'Расскажи первый аят суры Аль-Аля.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_alaq_1',
    title: 'Аль-Аляк',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 29,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Аль-Аляк означает «Сгусток крови». С этой мекканской суры началось ниспослание Корана: она велит читать во имя Господа, напоминает о сотворении человека и о том, что человек преступает границы, возомнив себя ни в чём не нуждающимся.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6107,
        arabicText: 'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِى خَلَقَ',
        transliteration: "Икра' бисми раббикаллязи халак",
        russianText: 'Читай во имя Господа твоего, Который сотворил',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6108,
        arabicText: 'خَلَقَ الْإِنسَٰنَ مِنْ عَلَقٍ',
        transliteration: "Халакаль-инсана мин 'аляк",
        russianText: 'сотворил человека из сгустка крови',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6109,
        arabicText: 'اقْرَأْ وَرَبُّكَ الْأَكْرَمُ',
        transliteration: "Икра' ва раббукаль-акрам",
        russianText: 'Читай, ведь твой Господь — Самый великодушный',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6110,
        arabicText: 'الَّذِى عَلَّمَ بِالْقَلَمِ',
        transliteration: "Аллязи 'аллама биль-калям",
        russianText: 'Который научил посредством письменной трости',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6111,
        arabicText: 'عَلَّمَ الْإِنسَٰنَ مَا لَمْ يَعْلَمْ',
        transliteration: "'Алламаль-инсана ма лям я'лям",
        russianText: 'научил человека тому, чего он не знал',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6112,
        arabicText: 'كَلَّآ إِنَّ الْإِنسَٰنَ لَيَطْغَىٰٓ',
        transliteration: 'Калля инналь-инсана ляятга',
        russianText: 'Но нет! Человек преступает границы дозволенного',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6113,
        arabicText: 'أَن رَّءَاهُ اسْتَغْنَىٰٓ',
        transliteration: 'Ар-рааху-стагна',
        russianText: 'когда ему кажется, что он ни в чём не нуждается',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6114,
        arabicText: 'إِنَّ إِلَىٰ رَبِّكَ الرُّجْعَىٰٓ',
        transliteration: "Инна иля раббикар-рудж'а",
        russianText: 'Воистину, к твоему Господу предстоит возвращение',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6115,
        arabicText: 'أَرَءَيْتَ الَّذِى يَنْهَىٰ',
        transliteration: "Ара'айталлязи янха",
        russianText: 'Видел ли ты того, кто запрещает',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6116,
        arabicText: 'عَبْدًا إِذَا صَلَّىٰٓ',
        transliteration: "'Абдан иза салля",
        russianText: 'рабу, когда тот молится?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6117,
        arabicText: 'أَرَءَيْتَ إِن كَانَ عَلَى الْهُدَىٰٓ',
        transliteration: "Ара'айта ин кана 'аляль-худа",
        russianText: 'Что ты думаешь, а вдруг он был на прямом пути',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6118,
        arabicText: 'أَوْ أَمَرَ بِالتَّقْوَىٰٓ',
        transliteration: 'Ау амара бит-таква',
        russianText: 'или призывал к богобоязненности?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6119,
        arabicText: 'أَرَءَيْتَ إِن كَذَّبَ وَتَوَلَّىٰٓ',
        transliteration: "Ара'айта ин каззаба ва тавалля",
        russianText:
            'Что ты думаешь, а вдруг он счёл истину ложью и отвернулся?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6120,
        arabicText: 'أَلَمْ يَعْلَم بِأَنَّ اللَّهَ يَرَىٰ',
        transliteration: "Алям я'лям би'анналлаха яра",
        russianText: 'Неужели он не знал, что Аллах видит его?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6121,
        arabicText: 'كَلَّا لَئِن لَّمْ يَنتَهِ لَنَسْفَعًۢا بِالنَّاصِيَةِ',
        transliteration: "Калля ляил лям янтахи лянасфа'ам бин-насия",
        russianText: 'Но нет! Если он не прекратит, Мы схватим его за хохол',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6122,
        arabicText: 'نَاصِيَةٍۢ كَٰذِبَةٍ خَاطِئَةٍۢ',
        transliteration: 'Насиятин казибатин хатыа',
        russianText: 'хохол лживый, грешный',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6123,
        arabicText: 'فَلْيَدْعُ نَادِيَهُۥ',
        transliteration: "Фальяд'у надияh",
        russianText: 'Пусть он зовёт на помощь своих сообщников',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6124,
        arabicText: 'سَنَدْعُ الزَّبَانِيَةَ',
        transliteration: "Санад'уз-забания",
        russianText: 'Мы же позовём стражей Ада',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6125,
        arabicText: 'كَلَّا لَا تُطِعْهُ وَاسْجُدْ وَاقْتَرِب ۩',
        transliteration: "Калля ля тути'hу васджуд вактариб",
        russianText:
            'Но нет! Не повинуйся ему, а пади ниц и приближайся к Аллаху',
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'С какого повеления начинается сура Аль-Аляк?',
        answers: [
          '«Читай во имя Господа твоего, Который сотворил»',
          '«Славь имя Господа твоего Всевышнего»',
          '«Клянусь предвечерним временем»',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Из чего, по суре, сотворён человек?',
        answers: [
          "Из сгустка крови ('аляк)",
          'Из капли изливающейся жидкости',
          'Из сухой звонкой глины',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Чему научил человека Господь, «Который научил посредством письменной трости»?',
        answers: [
          'Тому, чего человек не знал',
          'Счёту дней и ночей',
          'Именам всех ангелов',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Заполни пропуск: «Человек преступает границы, когда ему кажется, что он ни в чём не ___»',
        answers: [
          'нуждается',
          'виноват',
          'сомневается',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем завершается сура Аль-Аляк?',
        answers: [
          'Повелением пасть ниц и приближаться к Аллаху',
          'Обещанием изобилия (аль-Каусар)',
          'Клятвой смоковницей и оливой',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: "Икра' бисми раббикаллязи халак",
              answer: 'Читай во имя Господа твоего, Который сотворил'),
          LessonMatchPair(
              prompt: "Халакаль-инсана мин 'аляк",
              answer: 'сотворил человека из сгустка крови'),
          LessonMatchPair(
              prompt: "Икра' ва раббукаль-акрам",
              answer: 'Читай, ведь твой Господь — Самый великодушный'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 6107,
        arabicText: 'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِى خَلَقَ',
        transliteration: "Икра' бисми раббикаллязи халак",
        russianText: 'Расскажи первый аят суры Аль-Аляк.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_shams_1',
    title: 'Аш-Шамс',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 30,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Аш-Шамс означает «Солнце». Мекканская сура начинается с череды клятв солнцем, луной, днём, ночью, небом, землёй и душой, а завершается судьбой самудян: преуспел тот, кто очистил свою душу, и погиб тот, кто погряз в грехе.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6044,
        arabicText: 'وَالشَّمْسِ وَضُحَىٰهَا',
        transliteration: 'Ваш-шамси ва духаха',
        russianText: 'Клянусь солнцем и его утренним сиянием',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6045,
        arabicText: 'وَالْقَمَرِ إِذَا تَلَىٰهَا',
        transliteration: 'Валь-камари иза таляха',
        russianText: 'Клянусь луной, которая следует за ним',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6046,
        arabicText: 'وَالنَّهَارِ إِذَا جَلَّىٰهَا',
        transliteration: 'Ван-нахари иза джалляха',
        russianText: 'Клянусь днём, который делает его ясным',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6047,
        arabicText: 'وَالَّيْلِ إِذَا يَغْشَىٰهَا',
        transliteration: 'Валь-ляйли иза ягшаха',
        russianText: 'Клянусь ночью, которая его покрывает',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6048,
        arabicText: 'وَالسَّمَآءِ وَمَا بَنَىٰهَا',
        transliteration: 'Вас-самаи ва ма банаха',
        russianText: 'Клянусь небом и Тем, Кто его построил',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6049,
        arabicText: 'وَالْأَرْضِ وَمَا طَحَىٰهَا',
        transliteration: 'Валь-арды ва ма тахаха',
        russianText: 'Клянусь землёй и Тем, Кто её распростёр',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6050,
        arabicText: 'وَنَفْسٍۢ وَمَا سَوَّىٰهَا',
        transliteration: 'Ва нафсин ва ма савваха',
        russianText: 'Клянусь душой и Тем, Кто придал ей соразмерность',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6051,
        arabicText: 'فَأَلْهَمَهَا فُجُورَهَا وَتَقْوَىٰهَا',
        transliteration: 'Фа-альхамаха фуджураха ва таква ха',
        russianText: 'и внушил ей её грехи и её богобоязненность',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6052,
        arabicText: 'قَدْ أَفْلَحَ مَن زَكَّىٰهَا',
        transliteration: 'Кад афляха ман заккаха',
        russianText: 'Преуспел тот, кто очистил её',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6053,
        arabicText: 'وَقَدْ خَابَ مَن دَسَّىٰهَا',
        transliteration: 'Ва кад хаба ман дассаха',
        russianText: 'и понёс урон тот, кто скрыл её во грехе',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6054,
        arabicText: 'كَذَّبَتْ ثَمُودُ بِطَغْوَىٰهَآ',
        transliteration: 'Каззабат самуду битагваха',
        russianText: 'Самудяне сочли пророка лжецом из-за своего беззакония',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6055,
        arabicText: 'إِذِ انۢبَعَثَ أَشْقَىٰهَا',
        transliteration: "Изин-ба'аса ашкаха",
        russianText: 'когда самый несчастный из них вызвался убить верблюдицу',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6056,
        arabicText:
            'فَقَالَ لَهُمْ رَسُولُ اللَّهِ نَاقَةَ اللَّهِ وَسُقْيَٰهَا',
        transliteration: 'Факаля ляхум расулуллахи накаталлахи ва сукйаха',
        russianText:
            'Посланник Аллаха сказал им: «Берегите верблюдицу Аллаха и её питьё!»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6057,
        arabicText:
            'فَكَذَّبُوهُ فَعَقَرُوهَا فَدَمْدَمَ عَلَيْهِمْ رَبُّهُم بِذَنۢبِهِمْ فَسَوَّىٰهَا',
        transliteration:
            "Факаззабуху фа'акаруха фадамдама 'аляйхим раббухум бизанбихим фасавваха",
        russianText:
            'Они сочли его лжецом и зарезали её, и Господь погубил их за грех и сровнял их с землёй',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6058,
        arabicText: 'وَلَا يَخَافُ عُقْبَٰهَا',
        transliteration: "Ва ля яхафу 'укбаха",
        russianText: 'и не опасался Он последствий этого',
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем клянётся начало суры Аш-Шамс?',
        answers: [
          'Солнцем, луной, днём и ночью',
          'Зарёй и десятью ночами',
          'Небом и ночным путником',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Кто, по суре Аш-Шамс, преуспел?',
        answers: [
          'Тот, кто очистил свою душу',
          'Тот, кто накопил больше всех',
          'Тот, кто прожил долгую жизнь',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'За что были погублены самудяне?',
        answers: [
          'За то, что сочли пророка лжецом и зарезали верблюдицу',
          'За поклонение слону',
          'За то, что не кормили сироту',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Преуспел тот, кто ___ её (душу)»',
        answers: [
          'очистил',
          'унизил',
          'забыл',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Что противопоставлено в суре: «Преуспел тот, кто очистил душу»?',
        answers: [
          '«и понёс урон тот, кто скрыл её во грехе»',
          '«хотя Последняя жизнь лучше и вечнее»',
          '«и уклонится от него самый несчастный»',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Ваш-шамси ва духаха',
              answer: 'Клянусь солнцем и его утренним сиянием'),
          LessonMatchPair(
              prompt: 'Кад афляха ман заккаха',
              answer: 'Преуспел тот, кто очистил душу'),
          LessonMatchPair(
              prompt: 'Каззабат самуду битагваха',
              answer: 'Самудяне сочли пророка лжецом'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 6044,
        arabicText: 'وَالشَّمْسِ وَضُحَىٰهَا',
        transliteration: 'Ваш-шамси ва духаха',
        russianText: 'Расскажи первый аят суры Аш-Шамс.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_layl_1',
    title: 'Аль-Лейль',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 31,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Аль-Лейль означает «Ночь». Мекканская сура клянётся ночью и днём и противопоставляет два пути: щедрого богобоязненного человека, которому облегчён путь к легчайшему, и скупца, отвергшего истину, которому облегчён путь к тягчайшему.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6059,
        arabicText: 'وَالَّيْلِ إِذَا يَغْشَىٰ',
        transliteration: 'Валь-ляйли иза ягша',
        russianText: 'Клянусь ночью, когда она покрывает мраком',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6060,
        arabicText: 'وَالنَّهَارِ إِذَا تَجَلَّىٰ',
        transliteration: 'Ван-нахари иза таджалля',
        russianText: 'Клянусь днём, когда он проясняется',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6061,
        arabicText: 'وَمَا خَلَقَ الذَّكَرَ وَالْأُنثَىٰٓ',
        transliteration: 'Ва ма халаказ-закара валь-унса',
        russianText: 'и Тем, Кто сотворил мужчину и женщину',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6062,
        arabicText: 'إِنَّ سَعْيَكُمْ لَشَتَّىٰ',
        transliteration: "Инна са'йакум ляшатта",
        russianText: 'Воистину, ваши стремления различны',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6063,
        arabicText: 'فَأَمَّا مَنْ أَعْطَىٰ وَاتَّقَىٰ',
        transliteration: "Фа-амма ман а'та ваттака",
        russianText: 'Тому, кто делал пожертвования и был богобоязнен',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6064,
        arabicText: 'وَصَدَّقَ بِالْحُسْنَىٰ',
        transliteration: 'Ва саддака биль-хусна',
        russianText: 'и признавал истинность прекраснейшего',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6065,
        arabicText: 'فَسَنُيَسِّرُهُۥ لِلْيُسْرَىٰ',
        transliteration: 'Фасануяссируху лиль-юсра',
        russianText: 'Мы облегчим путь к легчайшему',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6066,
        arabicText: 'وَأَمَّا مَنۢ بَخِلَ وَاسْتَغْنَىٰ',
        transliteration: 'Ва амма мам бахиля вастагна',
        russianText:
            'А тому, кто был скуп и полагал, что не нуждается в Аллахе',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6067,
        arabicText: 'وَكَذَّبَ بِالْحُسْنَىٰ',
        transliteration: 'Ва каззаба биль-хусна',
        russianText: 'и счёл ложью прекраснейшее',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6068,
        arabicText: 'فَسَنُيَسِّرُهُۥ لِلْعُسْرَىٰ',
        transliteration: "Фасануяссируху лиль-'усра",
        russianText: 'Мы облегчим путь к тягчайшему',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6069,
        arabicText: 'وَمَا يُغْنِى عَنْهُ مَالُهُۥٓ إِذَا تَرَدَّىٰٓ',
        transliteration: "Ва ма югни 'анху малуху иза тарадда",
        russianText: 'Не спасёт его богатство, когда он падёт в Огонь',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6070,
        arabicText: 'إِنَّ عَلَيْنَا لَلْهُدَىٰ',
        transliteration: "Инна 'аляйна ляль-худа",
        russianText: 'Воистину, Нам надлежит вести прямым путём',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6071,
        arabicText: 'وَإِنَّ لَنَا لَلْـَٔاخِرَةَ وَالْأُولَىٰ',
        transliteration: 'Ва инна ляна ляль-ахира валь-уля',
        russianText: 'Воистину, Нам принадлежит и Последняя, и первая жизнь',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6072,
        arabicText: 'فَأَنذَرْتُكُمْ نَارًۭا تَلَظَّىٰ',
        transliteration: 'Фа-анзартукум наран таляззa',
        russianText: 'Я предостерёг вас от пылающего Огня',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6073,
        arabicText: 'لَا يَصْلَىٰهَآ إِلَّا الْأَشْقَى',
        transliteration: 'Ля ясляха илляль-ашка',
        russianText: 'Войдёт в него только самый несчастный',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6074,
        arabicText: 'الَّذِى كَذَّبَ وَتَوَلَّىٰ',
        transliteration: 'Аллязи каззаба ва тавалля',
        russianText: 'который счёл истину ложью и отвернулся',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6075,
        arabicText: 'وَسَيُجَنَّبُهَا الْأَتْقَى',
        transliteration: 'Ва саюджаннабухаль-атка',
        russianText: 'Отдалён будет от него самый богобоязненный',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6076,
        arabicText: 'الَّذِى يُؤْتِى مَالَهُۥ يَتَزَكَّىٰ',
        transliteration: "Аллязи ю'ти малаху ятазакка",
        russianText: 'который раздаёт своё имущество, очищаясь',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6077,
        arabicText: 'وَمَا لِأَحَدٍ عِندَهُۥ مِن نِّعْمَةٍۢ تُجْزَىٰٓ',
        transliteration: "Ва ма ли-ахадин 'индаху мин ни'матин туджза",
        russianText: 'и всякую милость возмещает не ради награды',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6078,
        arabicText: 'إِلَّا ابْتِغَآءَ وَجْهِ رَبِّهِ الْأَعْلَىٰ',
        transliteration: "Илляб-тигаа ваджхи раббихиль-а'ля",
        russianText: 'а только из стремления к Лику Господа своего Всевышнего',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6079,
        arabicText: 'وَلَسَوْفَ يَرْضَىٰ',
        transliteration: 'Ва лясауфа ярда',
        russianText: 'И он непременно будет доволен',
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем клянётся начало суры Аль-Лейль?',
        answers: [
          'Ночью, днём и Тем, Кто сотворил мужчину и женщину',
          'Солнцем и его утренним сиянием',
          'Небом, обладателем созвездий',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Кому Аллах «облегчит путь к легчайшему»?',
        answers: [
          'Тому, кто давал милостыню, был богобоязнен и признавал истину',
          'Тому, кто был скуп и счёл истину ложью',
          'Тому, кто накопил больше всех',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Ради чего, по суре, богобоязненный раздаёт имущество?',
        answers: [
          'Ради Лика Господа своего Всевышнего',
          'Ради похвалы людей',
          'Ради возврата долга',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Заполни пропуск: «А тому, кто был скуп... Мы облегчим путь к ___»',
        answers: [
          'тягчайшему',
          'легчайшему',
          'изобилию',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Какие два пути противопоставляет сура Аль-Лейль?',
        answers: [
          'Путь щедрого и богобоязненного — и путь скупого, отвергшего истину',
          'Путь богатых торговцев — и путь бедняков',
          'Путь владельцев слона — и путь жителей Мекки',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Валь-ляйли иза ягша',
              answer: 'Клянусь ночью, когда она покрывает мраком'),
          LessonMatchPair(
              prompt: 'Фасануяссируху лиль-юсра',
              answer: 'Мы облегчим путь к легчайшему'),
          LessonMatchPair(
              prompt: "Фасануяссируху лиль-'усра",
              answer: 'Мы облегчим путь к тягчайшему'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 6059,
        arabicText: 'وَالَّيْلِ إِذَا يَغْشَىٰ',
        transliteration: 'Валь-ляйли иза ягша',
        russianText: 'Расскажи первый аят суры Аль-Лейль.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_fajr_1',
    title: 'Аль-Фаджр',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 32,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Аль-Фаджр означает «Заря». Мекканская сура клянётся зарёй и ночами, напоминает о гибели адитов, самудян и Фараона, порицает любовь к богатству и небрежение к сироте, а завершается радостным призывом к умиротворённой душе вернуться к Господу и войти в Рай.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5994,
        arabicText: 'وَالْفَجْرِ',
        transliteration: 'Валь-фаджр',
        russianText: 'Клянусь зарёй',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5995,
        arabicText: 'وَلَيَالٍ عَشْرٍۢ',
        transliteration: "Ва ляялин 'ашр",
        russianText: 'клянусь десятью ночами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5996,
        arabicText: 'وَالشَّفْعِ وَالْوَتْرِ',
        transliteration: "Ваш-шаф'и валь-ватр",
        russianText: 'клянусь чётом и нечётом',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5997,
        arabicText: 'وَالَّيْلِ إِذَا يَسْرِ',
        transliteration: 'Валь-ляйли иза яср',
        russianText: 'клянусь ночью, когда она уходит',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5998,
        arabicText: 'هَلْ فِى ذَٰلِكَ قَسَمٌۭ لِّذِى حِجْرٍ',
        transliteration: 'Халь фи заликя касамул лизи хиджр',
        russianText: 'Неужели этого не достаточно для обладающего разумом?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5999,
        arabicText: 'أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِعَادٍ',
        transliteration: "Алям тара кайфа фа'аля раббука би'ад",
        russianText: 'Разве ты не видел, как Господь твой поступил с адитами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6000,
        arabicText: 'إِرَمَ ذَاتِ الْعِمَادِ',
        transliteration: "Ирама затиль-'имад",
        russianText: 'народом Ирама, обладавшим колоннами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6001,
        arabicText: 'الَّتِى لَمْ يُخْلَقْ مِثْلُهَا فِى الْبِلَٰدِ',
        transliteration: 'Алляти лям юхляк мислюха филь-биляд',
        russianText: 'подобных которым не было создано в странах',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6002,
        arabicText: 'وَثَمُودَ الَّذِينَ جَابُوا۟ الصَّخْرَ بِالْوَادِ',
        transliteration: 'Ва самудаллязина джабус-сахра биль-вад',
        russianText: 'и с самудянами, которые высекали скалы в долине',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6003,
        arabicText: 'وَفِرْعَوْنَ ذِى الْأَوْتَادِ',
        transliteration: "Ва фир'ауна зиль-автад",
        russianText: 'и с Фараоном, обладателем кольев',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6004,
        arabicText: 'الَّذِينَ طَغَوْا۟ فِى الْبِلَٰدِ',
        transliteration: 'Аллязина тагау филь-биляд',
        russianText: 'которые преступали границы дозволенного в странах',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6005,
        arabicText: 'فَأَكْثَرُوا۟ فِيهَا الْفَسَادَ',
        transliteration: 'Фа-аксару фихаль-фасад',
        russianText: 'и умножали в них нечестие',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6006,
        arabicText: 'فَصَبَّ عَلَيْهِمْ رَبُّكَ سَوْطَ عَذَابٍ',
        transliteration: "Фасабба 'аляйхим раббука саута 'азаб",
        russianText: 'Тогда твой Господь обрушил на них бич мучений',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6007,
        arabicText: 'إِنَّ رَبَّكَ لَبِالْمِرْصَادِ',
        transliteration: 'Инна раббака лябиль-мирсад',
        russianText: 'Воистину, твой Господь наблюдает, как в засаде',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6008,
        arabicText:
            'فَأَمَّا الْإِنسَٰنُ إِذَا مَا ابْتَلَىٰهُ رَبُّهُۥ فَأَكْرَمَهُۥ وَنَعَّمَهُۥ فَيَقُولُ رَبِّىٓ أَكْرَمَنِ',
        transliteration:
            "Фа-аммаль-инсану иза мабталяху раббуху фа-акрамаху ва на''амаху файакулю рабби акраман",
        russianText:
            'Когда Господь испытывает человека, оказывая ему милость и одаряя благами, тот говорит: «Господь мой почтил меня!»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6009,
        arabicText:
            'وَأَمَّآ إِذَا مَا ابْتَلَىٰهُ فَقَدَرَ عَلَيْهِ رِزْقَهُۥ فَيَقُولُ رَبِّىٓ أَهَٰنَنِ',
        transliteration:
            "Ва амма иза мабталяху факадара 'аляйхи ризкаху файакулю рабби ахаанан",
        russianText:
            'Когда же Он испытывает его, ограничивая его в пропитании, тот говорит: «Господь мой унизил меня!»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6010,
        arabicText: 'كَلَّا ۖ بَل لَّا تُكْرِمُونَ الْيَتِيمَ',
        transliteration: 'Калля баль ля тукримуналь-ятим',
        russianText: 'Но нет! Вы сами не почитаете сироту',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6011,
        arabicText: 'وَلَا تَحَٰٓضُّونَ عَلَىٰ طَعَامِ الْمِسْكِينِ',
        transliteration: "Ва ля тахаддуна 'аля та'амиль-мискин",
        russianText: 'не побуждаете друг друга кормить бедняка',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6012,
        arabicText: 'وَتَأْكُلُونَ التُّرَاثَ أَكْلًۭا لَّمًّۭا',
        transliteration: "Ва та'кулюнат-тураса аклял ляммa",
        russianText: 'жадно пожираете наследство целиком',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6013,
        arabicText: 'وَتُحِبُّونَ الْمَالَ حُبًّۭا جَمًّۭا',
        transliteration: 'Ва тухиббуналь-маля хуббан джаммa',
        russianText: 'и любите богатство любовью безмерной',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6014,
        arabicText: 'كَلَّآ إِذَا دُكَّتِ الْأَرْضُ دَكًّۭا دَكًّۭا',
        transliteration: 'Калля иза дуккатиль-арду даккан даккa',
        russianText: 'Но нет! Когда земля будет раздроблена на куски',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6015,
        arabicText: 'وَجَآءَ رَبُّكَ وَالْمَلَكُ صَفًّۭا صَفًّۭا',
        transliteration: 'Ва джаа раббука валь-малаку саффан саффa',
        russianText: 'и придёт твой Господь с ангелами, выстроившимися рядами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6016,
        arabicText:
            'وَجِا۟ىٓءَ يَوْمَئِذٍۭ بِجَهَنَّمَ ۚ يَوْمَئِذٍۢ يَتَذَكَّرُ الْإِنسَٰنُ وَأَنَّىٰ لَهُ الذِّكْرَىٰ',
        transliteration:
            "Ва джиа йаума'изин биджаханнам, йаума'изин ятазаккаруль-инсану ва анна ляхуз-зикра",
        russianText:
            'и будет в тот день приведён Ад. В тот день человек помянет назидание, но к чему ему оно?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6017,
        arabicText: 'يَقُولُ يَٰلَيْتَنِى قَدَّمْتُ لِحَيَاتِى',
        transliteration: 'Йакулю йаляйтани каддамту лихаяти',
        russianText:
            'Он скажет: «О, если бы я приготовил что-нибудь для своей жизни!»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6018,
        arabicText: 'فَيَوْمَئِذٍۢ لَّا يُعَذِّبُ عَذَابَهُۥٓ أَحَدٌۭ',
        transliteration: "Файаума'изил ля ю'аззибу 'азабаху ахад",
        russianText: 'В тот день никто не причинит таких мучений, как Он',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6019,
        arabicText: 'وَلَا يُوثِقُ وَثَاقَهُۥٓ أَحَدٌۭ',
        transliteration: 'Ва ля юсику васакаху ахад',
        russianText: 'и никто не наложит таких оков, как Он',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6020,
        arabicText: 'يَٰٓأَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ',
        transliteration: "Йа-айятухан-нафсуль-мутма'инна",
        russianText: 'О обретшая покой душа!',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6021,
        arabicText: 'ارْجِعِىٓ إِلَىٰ رَبِّكِ رَاضِيَةًۭ مَّرْضِيَّةًۭ',
        transliteration: "Ирджи'и иля раббики радыятам мардыйя",
        russianText:
            'Вернись к своему Господу удовлетворённой и снискавшей довольство!',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6022,
        arabicText: 'فَادْخُلِى فِى عِبَٰدِى',
        transliteration: "Фадхули фи 'ибади",
        russianText: 'Войди в круг Моих рабов!',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 6023,
        arabicText: 'وَادْخُلِى جَنَّتِى',
        transliteration: 'Вадхули джаннати',
        russianText: 'И войди в Мой Рай!',
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Какие народы приводятся в суре Аль-Фаджр как пример наказания?',
        answers: [
          'Адиты (народ Ирама), самудяне и Фараон',
          'Владельцы слона и курайшиты',
          'Владельцы рва и воинства',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Что говорит человек, когда Господь одаряет его благами, а что — когда ограничивает удел?',
        answers: [
          '«Господь почтил меня» — и «Господь унизил меня»',
          '«Господь испытал меня» — и «Господь простил меня»',
          '«Я преуспел» — и «Я в убытке»',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'В чём сура упрекает людей?',
        answers: [
          'Не почитают сироту, не кормят бедняка и жадно любят богатство',
          'Клянутся ложными богами',
          'Забывают славить имя Господа',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Заполни пропуск: «О обретшая ___ душа! Вернись к своему Господу»',
        answers: [
          'покой',
          'богатство',
          'сомнение',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем завершается сура Аль-Фаджр?',
        answers: [
          'Обращением к умиротворённой душе войти в Рай',
          'Клятвой предвечерним временем',
          'Повелением зарезать верблюдицу',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(prompt: 'Валь-фаджр', answer: 'Клянусь зарёй'),
          LessonMatchPair(
              prompt: "Ирама затиль-'имад",
              answer: 'народом Ирама, обладавшим колоннами'),
          LessonMatchPair(
              prompt: "Йа-айятухан-нафсуль-мутма'инна",
              answer: 'О обретшая покой душа!'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5994,
        arabicText: 'وَالْفَجْرِ',
        transliteration: 'Валь-фаджр',
        russianText: 'Расскажи первый аят суры Аль-Фаджр.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_ghashiya_1',
    title: 'Аль-Гашия',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 33,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Аль-Гашия означает «Покрывающее» — одно из имён Дня воскресения. Мекканская сура рисует два исхода: поникшие, измученные лица в пылающем Огне и блаженные лица в возвышенном Саду, а затем призывает взглянуть на знамения творения.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5968,
        arabicText: 'هَلْ أَتَىٰكَ حَدِيثُ الْغَٰشِيَةِ',
        transliteration: 'Халь атака хадисуль-гашия',
        russianText: 'Дошёл ли до тебя рассказ о Покрывающем?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5969,
        arabicText: 'وُجُوهٌۭ يَوْمَئِذٍ خَٰشِعَةٌ',
        transliteration: "Вуджухуй йаума'изин хашиа",
        russianText: 'Одни лица в тот день будут поникшими',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5970,
        arabicText: 'عَامِلَةٌۭ نَّاصِبَةٌۭ',
        transliteration: "'Амилятун насыба",
        russianText: 'изнурёнными, утомлёнными',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5971,
        arabicText: 'تَصْلَىٰ نَارًا حَامِيَةًۭ',
        transliteration: 'Тасля наран хамия',
        russianText: 'Они будут гореть в пылающем Огне',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5972,
        arabicText: 'تُسْقَىٰ مِنْ عَيْنٍ ءَانِيَةٍۢ',
        transliteration: "Тускa мин 'айнин ания",
        russianText: 'и поить их будут из источника кипящего',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5973,
        arabicText: 'لَّيْسَ لَهُمْ طَعَامٌ إِلَّا مِن ضَرِيعٍۢ',
        transliteration: "Ляйса ляхум та'амун илля мин дари'",
        russianText: 'Не будет у них пищи, кроме ядовитых колючек',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5974,
        arabicText: 'لَّا يُسْمِنُ وَلَا يُغْنِى مِن جُوعٍۢ',
        transliteration: "Ля юсмину ва ля югни мин джу'",
        russianText: 'которые не насыщают и не утоляют голода',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5975,
        arabicText: 'وُجُوهٌۭ يَوْمَئِذٍۢ نَّاعِمَةٌۭ',
        transliteration: "Вуджухуй йаума'изин на'има",
        russianText: 'Другие лица в тот день будут блаженными',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5976,
        arabicText: 'لِّسَعْيِهَا رَاضِيَةٌۭ',
        transliteration: "Лиса'йиха радыя",
        russianText: 'Они будут довольны своими стараниями',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5977,
        arabicText: 'فِى جَنَّةٍ عَالِيَةٍۢ',
        transliteration: "Фи джаннатин 'алия",
        russianText: 'в Саду возвышенном',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5978,
        arabicText: 'لَّا تَسْمَعُ فِيهَا لَٰغِيَةًۭ',
        transliteration: "Ля тасма'у фиха лагия",
        russianText: 'где не услышат пустых речей',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5979,
        arabicText: 'فِيهَا عَيْنٌۭ جَارِيَةٌۭ',
        transliteration: "Фиха 'айнун джария",
        russianText: 'Там есть текущий источник',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5980,
        arabicText: 'فِيهَا سُرُرٌۭ مَّرْفُوعَةٌۭ',
        transliteration: 'Фиха сурурум марфуа',
        russianText: 'там воздвигнуты высокие ложа',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5981,
        arabicText: 'وَأَكْوَابٌۭ مَّوْضُوعَةٌۭ',
        transliteration: 'Ва аквабум маудуа',
        russianText: 'расставлены чаши',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5982,
        arabicText: 'وَنَمَارِقُ مَصْفُوفَةٌۭ',
        transliteration: 'Ва намарику масфуфа',
        russianText: 'разложены подушки',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5983,
        arabicText: 'وَزَرَابِىُّ مَبْثُوثَةٌ',
        transliteration: 'Ва зарабийю мабсуса',
        russianText: 'и разостланы ковры',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5984,
        arabicText: 'أَفَلَا يَنظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَتْ',
        transliteration: 'Афаля янзуруна иляль-ибили кайфа хуликат',
        russianText: 'Неужели они не смотрят на верблюдов — как они сотворены',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5985,
        arabicText: 'وَإِلَى السَّمَآءِ كَيْفَ رُفِعَتْ',
        transliteration: "Ва иляс-самаи кайфа руфи'ат",
        russianText: 'и на небо — как оно возвышено',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5986,
        arabicText: 'وَإِلَى الْجِبَالِ كَيْفَ نُصِبَتْ',
        transliteration: 'Ва иляль-джибали кайфа нусыбат',
        russianText: 'и на горы — как они водружены',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5987,
        arabicText: 'وَإِلَى الْأَرْضِ كَيْفَ سُطِحَتْ',
        transliteration: 'Ва иляль-арды кайфа сутыхат',
        russianText: 'и на землю — как она распростёрта?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5988,
        arabicText: 'فَذَكِّرْ إِنَّمَآ أَنتَ مُذَكِّرٌۭ',
        transliteration: 'Фазаккир иннама анта музаккир',
        russianText: 'Наставляй же, ведь ты — наставник',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5989,
        arabicText: 'لَّسْتَ عَلَيْهِم بِمُصَيْطِرٍ',
        transliteration: "Ляста 'аляйхим бимусайтыр",
        russianText: 'и ты не властен принуждать их',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5990,
        arabicText: 'إِلَّا مَن تَوَلَّىٰ وَكَفَرَ',
        transliteration: 'Илля ман тавалля ва кафар',
        russianText: 'А тех, кто отвернётся и не уверует',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5991,
        arabicText: 'فَيُعَذِّبُهُ اللَّهُ الْعَذَابَ الْأَكْبَرَ',
        transliteration: "Файу'аззибухуллахуль-'азабаль-акбар",
        russianText: 'Аллах подвергнет величайшим мучениям',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5992,
        arabicText: 'إِنَّ إِلَيْنَآ إِيَابَهُمْ',
        transliteration: 'Инна иляйна ийабахум',
        russianText: 'Воистину, к Нам они вернутся',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5993,
        arabicText: 'ثُمَّ إِنَّ عَلَيْنَا حِسَابَهُم',
        transliteration: "Сумма инна 'аляйна хисабахум",
        russianText: 'и затем Нам предстоит их сосчитать',
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'О чём предупреждает начало суры Аль-Гашия?',
        answers: [
          'О Дне воскресения — Покрывающем (ошеломляющем)',
          'О предвечернем времени',
          'О ночном путнике',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем будут поить обитателей Огня, по суре?',
        answers: [
          'Из источника кипящего',
          'Из чистого мёда',
          'Из текущего родника Рая',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'На какие творения сура призывает взглянуть как на знамения?',
        answers: [
          'На верблюдов, небо, горы и землю',
          'На солнце, луну и звёзды',
          'На реки, моря и облака',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Наставляй же, ведь ты — ___»',
        answers: [
          'наставник',
          'владыка',
          'свидетель',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Какие две группы лиц противопоставляет сура Аль-Гашия?',
        answers: [
          'Поникшие лица в Огне — и блаженные лица в возвышенном Саду',
          'Богатые торговцы — и бедняки',
          'Владельцы слона — и жители Мекки',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Халь атака хадисуль-гашия',
              answer: 'Дошёл ли до тебя рассказ о Покрывающем?'),
          LessonMatchPair(
              prompt: "Вуджухуй йаума'изин на'има",
              answer: 'Другие лица в тот день будут блаженными'),
          LessonMatchPair(
              prompt: 'Фазаккир иннама анта музаккир',
              answer: 'Наставляй же, ведь ты — наставник'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5968,
        arabicText: 'هَلْ أَتَىٰكَ حَدِيثُ الْغَٰشِيَةِ',
        transliteration: 'Халь атака хадисуль-гашия',
        russianText: 'Расскажи первый аят суры Аль-Гашия.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_tariq_1',
    title: 'Ат-Тарик',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 34,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Ат-Тарик означает «Ночной путник» — ярко сияющую звезду. Мекканская сура клянётся небом и звездой, напоминает, что над каждой душой есть хранитель, указывает на сотворение человека как довод воскрешения и утверждает, что Коран — различающее Слово, а не шутка.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5932,
        arabicText: 'وَالسَّمَآءِ وَالطَّارِقِ',
        transliteration: 'Вас-самаи ват-тарик',
        russianText: 'Клянусь небом и ночным путником',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5933,
        arabicText: 'وَمَآ أَدْرَىٰكَ مَا الطَّارِقُ',
        transliteration: 'Ва ма адрака мат-тарик',
        russianText: 'Откуда тебе знать, что такое ночной путник?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5934,
        arabicText: 'النَّجْمُ الثَّاقِبُ',
        transliteration: 'Ан-наджмус-сакиб',
        russianText: 'Это — пронизывающая мраком звезда',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5935,
        arabicText: 'إِن كُلُّ نَفْسٍۢ لَّمَّا عَلَيْهَا حَافِظٌۭ',
        transliteration: "Ин куллю нафсил ляммa 'аляйха хафиз",
        russianText: 'Нет души, при которой не было бы хранителя',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5936,
        arabicText: 'فَلْيَنظُرِ الْإِنسَٰنُ مِمَّ خُلِقَ',
        transliteration: 'Фальянзуриль-инсану мимма хулик',
        russianText: 'Пусть посмотрит человек, из чего он создан',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5937,
        arabicText: 'خُلِقَ مِن مَّآءٍۢ دَافِقٍۢ',
        transliteration: 'Хулика мим маин дафик',
        russianText: 'Он создан из изливающейся жидкости',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5938,
        arabicText: 'يَخْرُجُ مِنۢ بَيْنِ الصُّلْبِ وَالتَّرَآئِبِ',
        transliteration: 'Йахруджу мим байнис-сульби ват-тараиб',
        russianText: 'которая выходит между поясницей и грудными костями',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5939,
        arabicText: 'إِنَّهُۥ عَلَىٰ رَجْعِهِۦ لَقَادِرٌۭ',
        transliteration: "Иннаху 'аля радж'ихи лякадир",
        russianText: 'Воистину, Он способен вернуть его к жизни',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5940,
        arabicText: 'يَوْمَ تُبْلَى السَّرَآئِرُ',
        transliteration: 'Йаума тублас-сараир',
        russianText: 'В тот день, когда будут раскрыты тайны',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5941,
        arabicText: 'فَمَا لَهُۥ مِن قُوَّةٍۢ وَلَا نَاصِرٍۢ',
        transliteration: 'Фама ляху мин куввaтин ва ля насыр',
        russianText: 'не будет у него ни силы, ни помощника',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5942,
        arabicText: 'وَالسَّمَآءِ ذَاتِ الرَّجْعِ',
        transliteration: "Вас-самаи затир-радж'",
        russianText: 'Клянусь небом, возвращающим дождь',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5943,
        arabicText: 'وَالْأَرْضِ ذَاتِ الصَّدْعِ',
        transliteration: "Валь-арды затис-сад'",
        russianText: 'и землёй, раскалывающейся растениями',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5944,
        arabicText: 'إِنَّهُۥ لَقَوْلٌۭ فَصْلٌۭ',
        transliteration: 'Иннаху лякаулюн фасл',
        russianText: 'Воистину, это — Слово различающее',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5945,
        arabicText: 'وَمَا هُوَ بِالْهَزْلِ',
        transliteration: 'Ва ма хуа биль-хазл',
        russianText: 'а не шутка',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5946,
        arabicText: 'إِنَّهُمْ يَكِيدُونَ كَيْدًۭا',
        transliteration: 'Иннахум якидуна кайдa',
        russianText: 'Воистину, они замышляют козни',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5947,
        arabicText: 'وَأَكِيدُ كَيْدًۭا',
        transliteration: 'Ва акиду кайдa',
        russianText: 'и Я замышляю Свой план',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5948,
        arabicText: 'فَمَهِّلِ الْكَٰفِرِينَ أَمْهِلْهُمْ رُوَيْدًۢا',
        transliteration: 'Фамаххилиль-кафирина амхильхум рувайдa',
        russianText: 'Дай же неверующим отсрочку, повремени с ними немного',
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем клянётся начало суры Ат-Тарик?',
        answers: [
          'Небом и ночным путником (звездой)',
          'Солнцем и его сиянием',
          'Зарёй и десятью ночами',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Что сура говорит о каждой душе?',
        answers: [
          'При ней есть хранитель (ангел)',
          'Она будет жить вечно',
          'Она сотворена из глины',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'На что указывает сура, говоря «Пусть посмотрит человек, из чего он создан»?',
        answers: [
          'На то, что человек создан из изливающейся жидкости — и потому Аллах способен воскресить его',
          'На то, что человек создан из сгустка крови и станет прахом',
          'На то, что человек создан из огня',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Это — Слово ___, а не шутка»',
        answers: [
          'различающее',
          'забытое',
          'тайное',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем завершается сура Ат-Тарик?',
        answers: [
          'Повелением дать неверующим краткую отсрочку',
          'Обещанием Райских садов',
          'Клятвой чётом и нечётом',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Вас-самаи ват-тарик',
              answer: 'Клянусь небом и ночным путником'),
          LessonMatchPair(
              prompt: 'Ан-наджмус-сакиб',
              answer: 'Это — пронизывающая мраком звезда'),
          LessonMatchPair(
              prompt: 'Иннаху лякаулюн фасл',
              answer: 'Это — Слово различающее'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5932,
        arabicText: 'وَالسَّمَآءِ وَالطَّارِقِ',
        transliteration: 'Вас-самаи ват-тарик',
        russianText: 'Расскажи первый аят суры Ат-Тарик.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_buruj_1',
    title: 'Аль-Бурудж',
    subtitle: 'Учебный фрагмент • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 35,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Аль-Бурудж означает «Созвездия» (небесные башни). Мекканская сура клянётся небом со звёздами и рассказывает о «владельцах рва», сжигавших верующих за их веру, обещая мучителям Геенну, а уверовавшим — сады, и напоминает, что Коран хранится в Хранимой скрижали.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5910,
        arabicText: 'وَالسَّمَآءِ ذَاتِ الْبُرُوجِ',
        transliteration: 'Вас-самаи затиль-бурудж',
        russianText: 'Клянусь небом, обладателем созвездий',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5911,
        arabicText: 'وَالْيَوْمِ الْمَوْعُودِ',
        transliteration: "Валь-йаумиль-мау'уд",
        russianText: 'клянусь днём обещанным',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5912,
        arabicText: 'وَشَاهِدٍۢ وَمَشْهُودٍۢ',
        transliteration: 'Ва шахидин ва машхуд',
        russianText: 'клянусь свидетелем и засвидетельствованным',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5913,
        arabicText: 'قُتِلَ أَصْحَٰبُ الْأُخْدُودِ',
        transliteration: 'Кутиля асхабуль-ухдуд',
        russianText: 'Убиты будут владельцы рва',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5914,
        arabicText: 'النَّارِ ذَاتِ الْوَقُودِ',
        transliteration: 'Ан-нари затиль-вакуд',
        russianText: 'огня, обладающего растопкой',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5915,
        arabicText: 'إِذْ هُمْ عَلَيْهَا قُعُودٌۭ',
        transliteration: "Из хум 'аляйха ку'уд",
        russianText: 'когда они сидели у него',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5916,
        arabicText: 'وَهُمْ عَلَىٰ مَا يَفْعَلُونَ بِالْمُؤْمِنِينَ شُهُودٌۭ',
        transliteration: "Ва хум 'аля ма яф'алуна биль-му'минина шухуд",
        russianText: 'и сами свидетельствовали о том, что творили с верующими',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5917,
        arabicText:
            'وَمَا نَقَمُوا۟ مِنْهُمْ إِلَّآ أَن يُؤْمِنُوا۟ بِاللَّهِ الْعَزِيزِ الْحَمِيدِ',
        transliteration:
            "Ва ма накаму минхум илля ай йу'мину биллахиль-'азизиль-хамид",
        russianText:
            'Они мстили им только за то, что те уверовали в Аллаха, Могущественного, Достохвального',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5918,
        arabicText:
            'الَّذِى لَهُۥ مُلْكُ السَّمَٰوَٰتِ وَالْأَرْضِ ۚ وَاللَّهُ عَلَىٰ كُلِّ شَىْءٍۢ شَهِيدٌ',
        transliteration:
            "Аллязи ляху мулькус-самавати валь-ард, валлаху 'аля кулли шайин шахид",
        russianText:
            'Которому принадлежит власть над небесами и землёй. Аллах — Свидетель всякой вещи',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5919,
        arabicText:
            'إِنَّ الَّذِينَ فَتَنُوا۟ الْمُؤْمِنِينَ وَالْمُؤْمِنَٰتِ ثُمَّ لَمْ يَتُوبُوا۟ فَلَهُمْ عَذَابُ جَهَنَّمَ وَلَهُمْ عَذَابُ الْحَرِيقِ',
        transliteration:
            "Инналлязина фатануль-му'минина валь-му'минати сумма лям ятубу фаляхум 'азабу джаханнама ва ляхум 'азабуль-харик",
        russianText:
            'Тем, кто подвергал искушению верующих мужчин и женщин и не раскаялся, уготованы мучения в Геенне и мучения от обжигающего Огня',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5920,
        arabicText:
            'إِنَّ الَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ الصَّٰلِحَٰتِ لَهُمْ جَنَّٰتٌۭ تَجْرِى مِن تَحْتِهَا الْأَنْهَٰرُ ۚ ذَٰلِكَ الْفَوْزُ الْكَبِيرُ',
        transliteration:
            "Инналлязина аману ва 'амилюс-салихати ляхум джаннатун таджри мин тахтихаль-анхар, залика ль-фаузуль-кабир",
        russianText:
            'А тем, кто уверовал и творил добро, уготованы сады, где текут реки. Это — великое преуспеяние',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5921,
        arabicText: 'إِنَّ بَطْشَ رَبِّكَ لَشَدِيدٌ',
        transliteration: 'Инна батша раббика ляшадид',
        russianText: 'Воистину, Хватка твоего Господа сурова',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5922,
        arabicText: 'إِنَّهُۥ هُوَ يُبْدِئُ وَيُعِيدُ',
        transliteration: "Иннаху хуа юбди'у ва йу'ид",
        russianText: 'Воистину, Он начинает творение и повторяет его',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5923,
        arabicText: 'وَهُوَ الْغَفُورُ الْوَدُودُ',
        transliteration: 'Ва хуаль-гафуруль-вадуд',
        russianText: 'Он — Прощающий, Любящий',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5924,
        arabicText: 'ذُو الْعَرْشِ الْمَجِيدُ',
        transliteration: "Зуль-'аршиль-маджид",
        russianText: 'Владыка Трона, Славный',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5925,
        arabicText: 'فَعَّالٌۭ لِّمَا يُرِيدُ',
        transliteration: "Фа''алюл лима юрид",
        russianText: 'вершащий то, что пожелает',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5926,
        arabicText: 'هَلْ أَتَىٰكَ حَدِيثُ الْجُنُودِ',
        transliteration: 'Халь атака хадисуль-джунуд',
        russianText: 'Дошёл ли до тебя рассказ о воинствах',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5927,
        arabicText: 'فِرْعَوْنَ وَثَمُودَ',
        transliteration: "Фир'ауна ва самуд",
        russianText: 'о Фараоне и самудянах?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5928,
        arabicText: 'بَلِ الَّذِينَ كَفَرُوا۟ فِى تَكْذِيبٍۢ',
        transliteration: 'Балиль-лязина кафару фи такзиб',
        russianText: 'Но неверующие продолжают считать это ложью',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5929,
        arabicText: 'وَاللَّهُ مِن وَرَآئِهِم مُّحِيطٌۢ',
        transliteration: 'Валлаху мин вараихим мухит',
        russianText: 'Аллах же объемлет их со всех сторон',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5930,
        arabicText: 'بَلْ هُوَ قُرْءَانٌۭ مَّجِيدٌۭ',
        transliteration: "Баль хуа кур'анум маджид",
        russianText: 'Да, это — славный Коран',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5931,
        arabicText: 'فِى لَوْحٍۢ مَّحْفُوظٍۭ',
        transliteration: 'Фи ляухим махфуз',
        russianText: 'в Хранимой скрижали',
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем клянётся начало суры Аль-Бурудж?',
        answers: [
          'Небом, обладателем созвездий, и днём обещанным',
          'Солнцем и луной',
          'Смоковницей и оливой',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Кто такие «владельцы рва», упомянутые в суре?',
        answers: [
          'Те, кто сжигал верующих в огне за их веру',
          'Владельцы стада верблюдов',
          'Войско, шедшее на Мекку со слоном',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'За что «владельцы рва» мстили верующим?',
        answers: [
          'Только за то, что те уверовали в Аллаха',
          'За неуплату дани',
          'За порчу их посевов',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Да, это — славный Коран, в Хранимой ___»',
        answers: [
          'скрижали',
          'пещере',
          'гавани',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Какие два воздаяния противопоставляет сура Аль-Бурудж?',
        answers: [
          'Мучения Геенны для мучителей — и сады с реками для уверовавших',
          'Богатство для щедрых — и бедность для скупых',
          'Долгую жизнь — и раннюю смерть',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Вас-самаи затиль-бурудж',
              answer: 'Клянусь небом, обладателем созвездий'),
          LessonMatchPair(
              prompt: 'Кутиля асхабуль-ухдуд',
              answer: 'Убиты будут владельцы рва'),
          LessonMatchPair(
              prompt: 'Ва хуаль-гафуруль-вадуд',
              answer: 'Он — Прощающий, Любящий'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5910,
        arabicText: 'وَالسَّمَآءِ ذَاتِ الْبُرُوجِ',
        transliteration: 'Вас-самаи затиль-бурудж',
        russianText: 'Расскажи первый аят суры Аль-Бурудж.',
      ),
    ],
  ),
];
