import '../../models/lesson.dart';

final List<Lesson> quranJuzAmmaA = [
  const Lesson(
    id: 'q_naba_1',
    title: 'Ан-Наба, часть 1',
    subtitle: 'Аяты 1–20 • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 36,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Ан-Наба означает «Весть». Мекканская сура открывает Джуз Амма вопросом: о чём спорят люди? О великой вести — воскрешении. Первая половина перечисляет знамения Аллаха в творении: земля-ложе, горы-колышки, сон-отдых, ночь-покрывало, семь твердынь, солнце-светильник, дождь и сады — и подводит к Дню различения.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5673,
        arabicText: 'عَمَّ يَتَسَآءَلُونَ',
        transliteration: 'Амма ятасаалюн',
        russianText: 'О чём они расспрашивают друг друга?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5674,
        arabicText: 'عَنِ النَّبَإِ الْعَظِيمِ',
        transliteration: "Анин-набаиль-'азым",
        russianText: 'О великой вести',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5675,
        arabicText: 'الَّذِى هُمْ فِيهِ مُخْتَلِفُونَ',
        transliteration: 'Аллязи хум фихи мухталифун',
        russianText: 'относительно которой они расходятся во мнениях',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5676,
        arabicText: 'كَلَّا سَيَعْلَمُونَ',
        transliteration: "Калля сая'лямун",
        russianText: 'Но нет, они узнают!',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5677,
        arabicText: 'ثُمَّ كَلَّا سَيَعْلَمُونَ',
        transliteration: "Сумма калля сая'лямун",
        russianText: 'Ещё раз нет, они узнают!',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5678,
        arabicText: 'أَلَمْ نَجْعَلِ الْأَرْضَ مِهَٰدًۭا',
        transliteration: "Алям надж'алиль-арда михада",
        russianText: 'Разве Мы не сделали землю ложем',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5679,
        arabicText: 'وَالْجِبَالَ أَوْتَادًۭا',
        transliteration: 'Валь-джибаля автада',
        russianText: 'а горы — колышками?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5680,
        arabicText: 'وَخَلَقْنَٰكُمْ أَزْوَٰجًۭا',
        transliteration: 'Ва халякнакум азваджа',
        russianText: 'Мы сотворили вас парами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5681,
        arabicText: 'وَجَعَلْنَا نَوْمَكُمْ سُبَاتًۭا',
        transliteration: "Ва джа'альна наумакум субата",
        russianText: 'и сделали ваш сон отдыхом',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5682,
        arabicText: 'وَجَعَلْنَا الَّيْلَ لِبَاسًۭا',
        transliteration: "Ва джа'альналь-лейля либаса",
        russianText: 'и сделали ночь покрывалом',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5683,
        arabicText: 'وَجَعَلْنَا النَّهَارَ مَعَاشًۭا',
        transliteration: "Ва джа'альнан-нахара ма'аша",
        russianText: 'и сделали день временем для заработка',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5684,
        arabicText: 'وَبَنَيْنَا فَوْقَكُمْ سَبْعًۭا شِدَادًۭا',
        transliteration: "Ва банайна фаукакум саб'ан шидада",
        russianText: 'Мы воздвигли над вами семь твердынь',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5685,
        arabicText: 'وَجَعَلْنَا سِرَاجًۭا وَهَّاجًۭا',
        transliteration: "Ва джа'альна сираджан ваххаджа",
        russianText: 'и установили пылающий светильник',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5686,
        arabicText: 'وَأَنزَلْنَا مِنَ الْمُعْصِرَٰتِ مَآءًۭ ثَجَّاجًۭا',
        transliteration: "Ва анзальна миналь-му'сырати маан саджджаджа",
        russianText: 'Мы низвели из облаков обильно льющуюся воду',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5687,
        arabicText: 'لِّنُخْرِجَ بِهِۦ حَبًّۭا وَنَبَاتًۭا',
        transliteration: 'Линухриджа бихи хаббан ва набата',
        russianText: 'чтобы взрастить ею зёрна и растения',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5688,
        arabicText: 'وَجَنَّٰتٍ أَلْفَافًا',
        transliteration: 'Ва джаннатин альфафа',
        russianText: 'и густые сады',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5689,
        arabicText: 'إِنَّ يَوْمَ الْفَصْلِ كَانَ مِيقَٰتًۭا',
        transliteration: 'Инна яумаль-фасли кана микaта',
        russianText: 'Воистину, День различения наступит в назначенный срок',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5690,
        arabicText: 'يَوْمَ يُنفَخُ فِى الصُّورِ فَتَأْتُونَ أَفْوَاجًۭا',
        transliteration: "Яума юнфаху фис-сури фата'туна афваджа",
        russianText: 'В тот день затрубят в Рог, и вы придёте толпами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5691,
        arabicText: 'وَفُتِحَتِ السَّمَآءُ فَكَانَتْ أَبْوَٰبًۭا',
        transliteration: 'Ва футихатис-самау факанат абваба',
        russianText: 'и небо раскроется и станет вратами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5692,
        arabicText: 'وَسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَابًا',
        transliteration: 'Ва суййиратиль-джибалю факанат сараба',
        russianText: 'и горы придут в движение и станут маревом',
      ),
      LessonStep(
        type: LessonStepType.listenChoice,
        quranGlobalAyahNumber: 5673,
        arabicText: 'عَمَّ يَتَسَآءَلُونَ',
        question: 'Прослушай аят и выбери его перевод',
        answers: [
          'О чём они расспрашивают друг друга?',
          'Клянусь небом и ночным путником',
          'Разве Мы не сделали землю ложем?',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.wordOrder,
        question: 'Собери шестой аят суры',
        russianText: 'Разве Мы не сделали землю ложем',
        orderTokens: [
          'أَلَمْ',
          'نَجْعَلِ',
          'الْأَرْضَ',
          'مِهَٰدًۭا',
        ],
        extraTokens: [
          'أَوْتَادًۭا',
        ],
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'О какой «великой вести» спорят люди в начале суры Ан-Наба?',
        answers: [
          'О воскрешении и Дне суда',
          'О переселении в Медину',
          'О разделе военной добычи',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'С чем сура сравнивает горы?',
        answers: [
          'С колышками, удерживающими землю',
          'С вратами небес',
          'С пылающими светильниками',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Мы сделали ваш сон ___»',
        answers: [
          'отдыхом',
          'наказанием',
          'испытанием',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Что названо в суре «пылающим светильником»?',
        answers: [
          'Солнце',
          'Луна',
          'Молния',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Что происходит с горами в День различения по аяту 20?',
        answers: [
          'Они приходят в движение и становятся маревом',
          'Они превращаются в сады',
          'Они остаются неподвижными',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Амма ятасаалюн',
              answer: 'О чём они расспрашивают друг друга?'),
          LessonMatchPair(
              prompt: 'Валь-джибаля автада', answer: 'а горы — колышками?'),
          LessonMatchPair(
              prompt: 'Ва джаннатин альфафа', answer: 'и густые сады'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5673,
        arabicText: 'عَمَّ يَتَسَآءَلُونَ',
        transliteration: 'Амма ятасаалюн',
        russianText: 'Расскажи первый аят суры Ан-Наба.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_naba_2',
    title: 'Ан-Наба, часть 2',
    subtitle: 'Аяты 21–40 • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 37,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Вторая половина суры Ан-Наба показывает две дороги Дня различения: Геенна как засада для преступивших границы — и успех богобоязненных с садами, виноградниками и полными чашами, где не услышать ни пустословия, ни лжи. Завершается сура предостережением о близком наказании и словами неверующего: «Лучше бы мне быть прахом!»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5693,
        arabicText: 'إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًۭا',
        transliteration: 'Инна джаханнама канат мирсада',
        russianText: 'Воистину, Геенна стала местом засады',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5694,
        arabicText: 'لِّلطَّٰغِينَ مَـَٔابًۭا',
        transliteration: 'Лит-тагина маaба',
        russianText: 'пристанищем для преступивших границы',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5695,
        arabicText: 'لَّٰبِثِينَ فِيهَآ أَحْقَابًۭا',
        transliteration: 'Лябисина фиха ахкаба',
        russianText: 'Они пробудут там долгие века',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5696,
        arabicText: 'لَّا يَذُوقُونَ فِيهَا بَرْدًۭا وَلَا شَرَابًا',
        transliteration: 'Ля язукуна фиха бардан ва ля шараба',
        russianText: 'Они не вкусят там ни прохлады, ни питья',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5697,
        arabicText: 'إِلَّا حَمِيمًۭا وَغَسَّاقًۭا',
        transliteration: 'Илля хамиман ва гассака',
        russianText: 'кроме кипятка и гноя',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5698,
        arabicText: 'جَزَآءًۭ وِفَاقًا',
        transliteration: 'Джазаан вифака',
        russianText: 'Таково воздаяние по заслугам',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5699,
        arabicText: 'إِنَّهُمْ كَانُوا۟ لَا يَرْجُونَ حِسَابًۭا',
        transliteration: 'Иннахум кяню ля ярджуна хисаба',
        russianText: 'Воистину, они не ожидали расчёта',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5700,
        arabicText: 'وَكَذَّبُوا۟ بِـَٔايَٰتِنَا كِذَّابًۭا',
        transliteration: 'Ва каззабу би-аятина киззаба',
        russianText: 'и полностью отвергали Наши знамения',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5701,
        arabicText: 'وَكُلَّ شَىْءٍ أَحْصَيْنَٰهُ كِتَٰبًۭا',
        transliteration: 'Ва кулля шайин ахсайнаху китаба',
        russianText: 'Мы же всякую вещь подсчитали и записали',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5702,
        arabicText: 'فَذُوقُوا۟ فَلَن نَّزِيدَكُمْ إِلَّا عَذَابًا',
        transliteration: "Фазуку фалян назидакум илля 'азаба",
        russianText: 'Вкушайте же! Мы не прибавим вам ничего, кроме мучений',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5703,
        arabicText: 'إِنَّ لِلْمُتَّقِينَ مَفَازًا',
        transliteration: 'Инна лиль-муттакина мафаза',
        russianText: 'Воистину, богобоязненных ожидает успех',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5704,
        arabicText: 'حَدَآئِقَ وَأَعْنَٰبًۭا',
        transliteration: "Хадаика ва а'наба",
        russianText: 'сады и виноградники',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5705,
        arabicText: 'وَكَوَاعِبَ أَتْرَابًۭا',
        transliteration: "Ва кава'иба атраба",
        russianText: 'и сверстницы',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5706,
        arabicText: 'وَكَأْسًۭا دِهَاقًۭا',
        transliteration: "Ва ка'сан дихака",
        russianText: 'и полные чаши',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5707,
        arabicText: 'لَّا يَسْمَعُونَ فِيهَا لَغْوًۭا وَلَا كِذَّٰبًۭا',
        transliteration: "Ля ясма'уна фиха лягван ва ля киззаба",
        russianText: 'Они не услышат там ни пустословия, ни лжи',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5708,
        arabicText: 'جَزَآءًۭ مِّن رَّبِّكَ عَطَآءً حِسَابًۭا',
        transliteration: "Джазаан мир-раббика 'атаан хисаба",
        russianText: 'Это — воздаяние от твоего Господа, дар исчисленный',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5709,
        arabicText:
            'رَّبِّ السَّمَٰوَٰتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا الرَّحْمَٰنِ ۖ لَا يَمْلِكُونَ مِنْهُ خِطَابًۭا',
        transliteration:
            'Раббис-самавати валь-арды ва ма байнахумар-Рахман, ля ямликуна минху хитаба',
        russianText:
            'Господа небес и земли и того, что между ними, Милостивого, с Которым они не смеют заговорить',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5710,
        arabicText:
            'يَوْمَ يَقُومُ الرُّوحُ وَالْمَلَٰٓئِكَةُ صَفًّۭا ۖ لَّا يَتَكَلَّمُونَ إِلَّا مَنْ أَذِنَ لَهُ الرَّحْمَٰنُ وَقَالَ صَوَابًۭا',
        transliteration:
            'Яума якумур-руху валь-маляикату саффа, ля ятакаллямуна илля ман азина ляхур-Рахману ва каля саваба',
        russianText:
            'В тот день Дух и ангелы станут рядами. Не заговорит никто, кроме тех, кому позволит Милостивый, и скажет он правду',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5711,
        arabicText:
            'ذَٰلِكَ الْيَوْمُ الْحَقُّ ۖ فَمَن شَآءَ اتَّخَذَ إِلَىٰ رَبِّهِۦ مَـَٔابًا',
        transliteration:
            'Заликаль-яумуль-хакк, фаман шаа-ттахаза иля раббихи маaба',
        russianText:
            'Это — Истинный день. Кто хочет, тот найдёт путь к своему Господу',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5712,
        arabicText:
            'إِنَّآ أَنذَرْنَٰكُمْ عَذَابًۭا قَرِيبًۭا يَوْمَ يَنظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُولُ الْكَافِرُ يَٰلَيْتَنِى كُنتُ تُرَٰبًۢا',
        transliteration:
            "Инна анзарнакум 'азабан кариба, яума янзуруль-мар'у ма каддамат ядах, ва якулюль-кафиру я лейтани кунту тураба",
        russianText:
            'Мы предостерегли вас от близких мучений. В тот день человек увидит, что уготовили его руки, а неверующий скажет: «Лучше бы мне быть прахом!»',
      ),
      LessonStep(
        type: LessonStepType.listenChoice,
        quranGlobalAyahNumber: 5703,
        arabicText: 'إِنَّ لِلْمُتَّقِينَ مَفَازًا',
        question: 'Прослушай аят и выбери его перевод',
        answers: [
          'Воистину, богобоязненных ожидает успех',
          'Воистину, Геенна стала местом засады',
          'Таково воздаяние по заслугам',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.wordOrder,
        question: 'Собери аят 24 суры Ан-Наба',
        russianText: 'Они не вкусят там ни прохлады, ни питья',
        orderTokens: [
          'لَّا',
          'يَذُوقُونَ',
          'فِيهَا',
          'بَرْدًۭا',
          'وَلَا',
          'شَرَابًا',
        ],
        extraTokens: [
          'حَمِيمًۭا',
        ],
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Кому Геенна станет пристанищем по аятам 21–22?',
        answers: [
          'Преступившим границы дозволенного',
          'Всем без исключения',
          'Только тем, кто не совершал хадж',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Почему сура называет наказание «воздаянием по заслугам»?',
        answers: [
          'Они не ожидали расчёта и отвергали знамения',
          'Они были бедны',
          'Они жили в Мекке',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Мы всякую вещь подсчитали и ___»',
        answers: [
          'записали',
          'простили',
          'скрыли',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чего не услышат обитатели садов?',
        answers: [
          'Ни пустословия, ни лжи',
          'Ни пения птиц',
          'Ни шума воды',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Какими словами заканчивается сура Ан-Наба?',
        answers: [
          'Словами неверующего: «Лучше бы мне быть прахом!»',
          'Клятвой зарёй и десятью ночами',
          'Повелением совершать намаз',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Инна джаханнама канат мирсада',
              answer: 'Воистину, Геенна стала местом засады'),
          LessonMatchPair(
              prompt: 'Инна лиль-муттакина мафаза',
              answer: 'Воистину, богобоязненных ожидает успех'),
          LessonMatchPair(
              prompt: 'Джазаан вифака', answer: 'Таково воздаяние по заслугам'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5703,
        arabicText: 'إِنَّ لِلْمُتَّقِينَ مَفَازًا',
        transliteration: 'Инна лиль-муттакина мафаза',
        russianText: 'Расскажи аят 31 суры Ан-Наба.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_naziat_1',
    title: 'Ан-Назиат, часть 1',
    subtitle: 'Аяты 1–26 • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 38,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Ан-Назиат означает «Исторгающие» — так названы ангелы, забирающие души. Мекканская сура начинается пятью клятвами, описывает ужас воскрешения и приводит в пример историю Мусы и Фараона: Фараон сказал «Я — ваш всевышний господь», и Аллах покарал его в обоих мирах. В этом — назидание для богобоязненных.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5713,
        arabicText: 'وَالنَّٰزِعَٰتِ غَرْقًۭا',
        transliteration: "Ван-нази'ати гарка",
        russianText: 'Клянусь исторгающими души жёстко',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5714,
        arabicText: 'وَالنَّٰشِطَٰتِ نَشْطًۭا',
        transliteration: 'Ван-нашитати нашта',
        russianText: 'извлекающими души легко',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5715,
        arabicText: 'وَالسَّٰبِحَٰتِ سَبْحًۭا',
        transliteration: 'Вас-сабихати сабха',
        russianText: 'плывущими стремительно',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5716,
        arabicText: 'فَالسَّٰبِقَٰتِ سَبْقًۭا',
        transliteration: 'Фас-сабикати сабка',
        russianText: 'опережающими стремительно',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5717,
        arabicText: 'فَالْمُدَبِّرَٰتِ أَمْرًۭا',
        transliteration: 'Фаль-мудаббирати амра',
        russianText: 'и исполняющими повеления',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5718,
        arabicText: 'يَوْمَ تَرْجُفُ الرَّاجِفَةُ',
        transliteration: 'Яума тарджуфур-раджифа',
        russianText: 'В тот день сотрясётся сотрясающаяся',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5719,
        arabicText: 'تَتْبَعُهَا الرَّادِفَةُ',
        transliteration: "Татба'ухар-радифа",
        russianText: 'а за ней последует следующая',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5720,
        arabicText: 'قُلُوبٌۭ يَوْمَئِذٍۢ وَاجِفَةٌ',
        transliteration: 'Кулюбун яумаизин ваджифа',
        russianText: 'Сердца в тот день будут трепетать',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5721,
        arabicText: 'أَبْصَٰرُهَا خَٰشِعَةٌۭ',
        transliteration: "Абсаруха хаши'а",
        russianText: 'а взоры их будут смиренны',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5722,
        arabicText: 'يَقُولُونَ أَءِنَّا لَمَرْدُودُونَ فِى الْحَافِرَةِ',
        transliteration: 'Якулюна аинна лямардудуна филь-хафира',
        russianText: 'Они говорят: «Неужели мы вернёмся в прежнее состояние',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5723,
        arabicText: 'أَءِذَا كُنَّا عِظَٰمًۭا نَّخِرَةًۭ',
        transliteration: "Аиза кунна 'изаман нахира",
        russianText: 'после того как станем истлевшими костями?»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5724,
        arabicText: 'قَالُوا۟ تِلْكَ إِذًۭا كَرَّةٌ خَاسِرَةٌۭ',
        transliteration: 'Калю тилька изан карратун хасира',
        russianText: 'Они говорят: «Тогда это будет возвращением с убытком!»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5725,
        arabicText: 'فَإِنَّمَا هِىَ زَجْرَةٌۭ وَٰحِدَةٌۭ',
        transliteration: 'Фаиннама хия заджратун вахида',
        russianText: 'Но это будет лишь один окрик',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5726,
        arabicText: 'فَإِذَا هُم بِالسَّاهِرَةِ',
        transliteration: 'Фаиза хум бис-сахира',
        russianText: 'и вот они окажутся на поверхности земли',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5727,
        arabicText: 'هَلْ أَتَىٰكَ حَدِيثُ مُوسَىٰٓ',
        transliteration: 'Халь атака хадису Муса',
        russianText: 'Дошёл ли до тебя рассказ о Мусе?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5728,
        arabicText: 'إِذْ نَادَىٰهُ رَبُّهُۥ بِالْوَادِ الْمُقَدَّسِ طُوًى',
        transliteration: 'Из надаху раббуху биль-вадиль-мукаддаси Тува',
        russianText: 'Вот Господь его воззвал к нему в священной долине Тува',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5729,
        arabicText: 'اذْهَبْ إِلَىٰ فِرْعَوْنَ إِنَّهُۥ طَغَىٰ',
        transliteration: "Изхаб иля Фир'ауна иннаху тага",
        russianText:
            '«Ступай к Фараону, ибо он преступил границы дозволенного»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5730,
        arabicText: 'فَقُلْ هَل لَّكَ إِلَىٰٓ أَن تَزَكَّىٰ',
        transliteration: 'Факуль халь ляка иля ан тазакка',
        russianText: 'и скажи: «Не желаешь ли очиститься',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5731,
        arabicText: 'وَأَهْدِيَكَ إِلَىٰ رَبِّكَ فَتَخْشَىٰ',
        transliteration: 'Ва ахдияка иля раббика фатахша',
        russianText:
            'чтобы я указал тебе путь к твоему Господу и ты стал богобоязненным?»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5732,
        arabicText: 'فَأَرَىٰهُ الْـَٔايَةَ الْكُبْرَىٰ',
        transliteration: 'Фаараху аятал-кубра',
        russianText: 'Он показал ему величайшее знамение',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5733,
        arabicText: 'فَكَذَّبَ وَعَصَىٰ',
        transliteration: "Факаззаба ва 'аса",
        russianText: 'но тот счёл его ложью и ослушался',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5734,
        arabicText: 'ثُمَّ أَدْبَرَ يَسْعَىٰ',
        transliteration: "Сумма адбара яс'а",
        russianText: 'а потом отвернулся и принялся усердствовать',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5735,
        arabicText: 'فَحَشَرَ فَنَادَىٰ',
        transliteration: 'Фахашара фанада',
        russianText: 'Он собрал народ и воззвал',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5736,
        arabicText: 'فَقَالَ أَنَا۠ رَبُّكُمُ الْأَعْلَىٰ',
        transliteration: "Факаля ана раббукумуль-а'ля",
        russianText: 'и сказал: «Я — ваш всевышний господь!»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5737,
        arabicText: 'فَأَخَذَهُ اللَّهُ نَكَالَ الْـَٔاخِرَةِ وَالْأُولَىٰٓ',
        transliteration: 'Фаахазахуллаху накаляль-ахирати валь-уля',
        russianText:
            'Тогда Аллах покарал его наказанием в Последней жизни и в первой',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5738,
        arabicText: 'إِنَّ فِى ذَٰلِكَ لَعِبْرَةًۭ لِّمَن يَخْشَىٰٓ',
        transliteration: "Инна фи залика ля'ибратал лиман яхша",
        russianText: 'Воистину, в этом — назидание для того, кто богобоязнен',
      ),
      LessonStep(
        type: LessonStepType.listenChoice,
        quranGlobalAyahNumber: 5727,
        arabicText: 'هَلْ أَتَىٰكَ حَدِيثُ مُوسَىٰٓ',
        question: 'Прослушай аят и выбери его перевод',
        answers: [
          'Дошёл ли до тебя рассказ о Мусе?',
          'Дошёл ли до тебя рассказ о Покрывающем?',
          'Клянусь небом и ночным путником',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.wordOrder,
        question: 'Собери аят 15 суры Ан-Назиат',
        russianText: 'Дошёл ли до тебя рассказ о Мусе?',
        orderTokens: [
          'هَلْ',
          'أَتَىٰكَ',
          'حَدِيثُ',
          'مُوسَىٰٓ',
        ],
        extraTokens: [
          'إِلَىٰ',
        ],
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Кто такие «исторгающие», давшие имя суре?',
        answers: [
          'Ангелы, забирающие души',
          'Ветры пустыни',
          'Волны моря',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Что отвечали отрицающие воскрешение на весть о возвращении к жизни?',
        answers: [
          '«Неужели мы вернёмся, став истлевшими костями?»',
          '«Мы уверовали сразу»',
          '«Мы попросим отсрочку»',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Сколько окриков понадобится для воскрешения по аяту 13?',
        answers: [
          'Один',
          'Три',
          'Семь',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'В какой долине Аллах воззвал к Мусе?',
        answers: [
          'В священной долине Тува',
          'В долине Мина',
          'В долине Бакка',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Чем закончилась дерзость Фараона, сказавшего «Я — ваш всевышний господь»?',
        answers: [
          'Аллах покарал его в Последней жизни и в первой',
          'Он раскаялся и уверовал',
          'Он покинул Египет',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: "Ван-нази'ати гарка",
              answer: 'Клянусь исторгающими души жёстко'),
          LessonMatchPair(
              prompt: 'Халь атака хадису Муса',
              answer: 'Дошёл ли до тебя рассказ о Мусе?'),
          LessonMatchPair(
              prompt: "Изхаб иля Фир'ауна иннаху тага",
              answer: 'Ступай к Фараону, ибо он преступил границы'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5727,
        arabicText: 'هَلْ أَتَىٰكَ حَدِيثُ مُوسَىٰٓ',
        transliteration: 'Халь атака хадису Муса',
        russianText: 'Расскажи аят 15 суры Ан-Назиат.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_naziat_2',
    title: 'Ан-Назиат, часть 2',
    subtitle: 'Аяты 27–46 • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 39,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Вторая половина суры отвечает отрицающим воскрешение: сотворить небо, распростереть землю, вывести воду и пастбища — труднее, чем вернуть человека к жизни. Дальше сура делит людей надвое: преступивший границы и полюбивший мирское получит Ад, а боявшийся Господа и удержавший душу от страстей — Рай. О времени Часа знает только Аллах.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5739,
        arabicText: 'ءَأَنتُمْ أَشَدُّ خَلْقًا أَمِ السَّمَآءُ ۚ بَنَىٰهَا',
        transliteration: 'Аантум ашадду халькан амис-самау банаха',
        russianText: 'Вас ли труднее сотворить или небо? Он воздвиг его',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5740,
        arabicText: 'رَفَعَ سَمْكَهَا فَسَوَّىٰهَا',
        transliteration: 'Рафа’а самкаха фасавваха',
        russianText: 'поднял его свод и сделал его совершенным',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5741,
        arabicText: 'وَأَغْطَشَ لَيْلَهَا وَأَخْرَجَ ضُحَىٰهَا',
        transliteration: 'Ва агташа лейляха ва ахраджа духаха',
        russianText: 'Он сделал ночь его тёмной и вывел его утреннюю зарю',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5742,
        arabicText: 'وَالْأَرْضَ بَعْدَ ذَٰلِكَ دَحَىٰهَآ',
        transliteration: "Валь-арда ба'да залика дахаха",
        russianText: 'После этого Он распростёр землю',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5743,
        arabicText: 'أَخْرَجَ مِنْهَا مَآءَهَا وَمَرْعَىٰهَا',
        transliteration: "Ахраджа минха мааха ва мар'аха",
        russianText: 'вывел из неё воду и пастбища',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5744,
        arabicText: 'وَالْجِبَالَ أَرْسَىٰهَا',
        transliteration: 'Валь-джибаля арсаха',
        russianText: 'и утвердил горы',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5745,
        arabicText: 'مَتَٰعًۭا لَّكُمْ وَلِأَنْعَٰمِكُمْ',
        transliteration: "Мата'ал лякум ва ли ан'амикум",
        russianText: 'на пользу вам и вашему скоту',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5746,
        arabicText: 'فَإِذَا جَآءَتِ الطَّآمَّةُ الْكُبْرَىٰ',
        transliteration: 'Фаиза джаатит-таммату-ль-кубра',
        russianText: 'Когда же наступит Величайшее бедствие',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5747,
        arabicText: 'يَوْمَ يَتَذَكَّرُ الْإِنسَٰنُ مَا سَعَىٰ',
        transliteration: "Яума ятазаккаруль-инсану ма са'а",
        russianText: 'в тот день человек вспомнит о том, к чему стремился',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5748,
        arabicText: 'وَبُرِّزَتِ الْجَحِيمُ لِمَن يَرَىٰ',
        transliteration: 'Ва бурризатиль-джахиму лиман яра',
        russianText: 'и Ад будет показан тем, кто увидит',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5749,
        arabicText: 'فَأَمَّا مَن طَغَىٰ',
        transliteration: 'Фаамма ман тага',
        russianText: 'Тому, кто преступил границы дозволенного',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5750,
        arabicText: 'وَءَاثَرَ الْحَيَوٰةَ الدُّنْيَا',
        transliteration: 'Ва асараль-хаятад-дунья',
        russianText: 'и отдал предпочтение мирской жизни',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5751,
        arabicText: 'فَإِنَّ الْجَحِيمَ هِىَ الْمَأْوَىٰ',
        transliteration: "Фаиннал-джахима хияль-ма'ва",
        russianText: 'пристанищем будет Ад',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5752,
        arabicText:
            'وَأَمَّا مَنْ خَافَ مَقَامَ رَبِّهِۦ وَنَهَى النَّفْسَ عَنِ الْهَوَىٰ',
        transliteration:
            "Ва амма ман хафа макама раббихи ва нахан-нафса 'аниль-хава",
        russianText:
            'Тому же, кто боялся предстать перед своим Господом и удерживал душу от страстей',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5753,
        arabicText: 'فَإِنَّ الْجَنَّةَ هِىَ الْمَأْوَىٰ',
        transliteration: "Фаиннал-джанната хияль-ма'ва",
        russianText: 'пристанищем будет Рай',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5754,
        arabicText: 'يَسْـَٔلُونَكَ عَنِ السَّاعَةِ أَيَّانَ مُرْسَىٰهَا',
        transliteration: "Яс'алюнака 'анис-са'ати айяна мурсаха",
        russianText: 'Тебя спрашивают о Часе: «Когда он наступит?»',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5755,
        arabicText: 'فِيمَ أَنتَ مِن ذِكْرَىٰهَآ',
        transliteration: 'Фима анта мин зикраха',
        russianText: 'Тебе ли знать об этом?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5756,
        arabicText: 'إِلَىٰ رَبِّكَ مُنتَهَىٰهَآ',
        transliteration: 'Иля раббика мунтахаха',
        russianText: 'Только твой Господь знает его предел',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5757,
        arabicText: 'إِنَّمَآ أَنتَ مُنذِرُ مَن يَخْشَىٰهَا',
        transliteration: 'Иннама анта мунзиру ман яхшаха',
        russianText:
            'Ты — всего лишь предостерегающий для тех, кто страшится его',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5758,
        arabicText:
            'كَأَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوٓا۟ إِلَّا عَشِيَّةً أَوْ ضُحَىٰهَا',
        transliteration:
            "Кааннахум яума яраунаха лям ялбасу илля 'ашийятан ав духаха",
        russianText:
            'В тот день, когда они увидят его, им покажется, что они пробыли на земле лишь вечер или утро',
      ),
      LessonStep(
        type: LessonStepType.listenChoice,
        quranGlobalAyahNumber: 5753,
        arabicText: 'فَإِنَّ الْجَنَّةَ هِىَ الْمَأْوَىٰ',
        question: 'Прослушай аят и выбери его перевод',
        answers: [
          'пристанищем будет Рай',
          'пристанищем будет Ад',
          'и утвердил горы',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.wordOrder,
        question: 'Собери аят 41 суры Ан-Назиат',
        russianText: 'пристанищем будет Рай',
        orderTokens: [
          'فَإِنَّ',
          'الْجَنَّةَ',
          'هِىَ',
          'الْمَأْوَىٰ',
        ],
        extraTokens: [
          'الْجَحِيمَ',
        ],
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Какой довод в пользу воскрешения приводят аяты 27–33?',
        answers: [
          'Сотворение неба и земли труднее, чем воскрешение человека',
          'Долгая жизнь пророков',
          'Смена времён года',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Что вспомнит человек в день Величайшего бедствия?',
        answers: [
          'То, к чему он стремился при жизни',
          'Имена своих предков',
          'Дорогу домой',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Кому сура обещает Ад?',
        answers: [
          'Преступившему границы и предпочётшему мирскую жизнь',
          'Тому, кто был беден',
          'Тому, кто много спрашивал',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'Заполни пропуск: «Тому, кто боялся предстать перед Господом и удерживал душу от страстей, пристанищем будет ___»',
        answers: [
          'Рай',
          'Ад',
          'пустыня',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Что сура отвечает на вопрос «Когда наступит Час?»',
        answers: [
          'Знание о нём — только у Господа',
          'Он наступит через тысячу лет',
          'Он уже наступил',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Валь-джибаля арсаха', answer: 'и утвердил горы'),
          LessonMatchPair(
              prompt: "Фаиннал-джахима хияль-ма'ва",
              answer: 'пристанищем будет Ад'),
          LessonMatchPair(
              prompt: "Фаиннал-джанната хияль-ма'ва",
              answer: 'пристанищем будет Рай'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5753,
        arabicText: 'فَإِنَّ الْجَنَّةَ هِىَ الْمَأْوَىٰ',
        transliteration: "Фаиннал-джанната хияль-ма'ва",
        russianText: 'Расскажи аят 41 суры Ан-Назиат.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_abasa_1',
    title: 'Абаса, часть 1',
    subtitle: 'Аяты 1–23 • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 40,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Абаса означает «Нахмурился». Сура ниспослана о случае, когда во время разговора со знатью Мекки к Пророку ﷺ подошёл слепой сподвижник Абдуллах ибн Умм Мактум, ищущий знания, и остался без внимания. Аллах учит: искренне ищущий истину дороже равнодушного богача. Дальше сура напоминает человеку, из чего он создан.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5759,
        arabicText: 'عَبَسَ وَتَوَلَّىٰٓ',
        transliteration: "'Абаса ва тавалля",
        russianText: 'Он нахмурился и отвернулся',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5760,
        arabicText: 'أَن جَآءَهُ الْأَعْمَىٰ',
        transliteration: "ан джаахуль-а'ма",
        russianText: 'оттого, что к нему подошёл слепой',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5761,
        arabicText: 'وَمَا يُدْرِيكَ لَعَلَّهُۥ يَزَّكَّىٰٓ',
        transliteration: "Ва ма юдрика ля'алляху язакка",
        russianText: 'Откуда тебе знать? Возможно, он бы очистился',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5762,
        arabicText: 'أَوْ يَذَّكَّرُ فَتَنفَعَهُ الذِّكْرَىٰٓ',
        transliteration: "ав язаккару фатанфа'ахуз-зикра",
        russianText: 'или помянул бы назидание, и оно принесло бы ему пользу',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5763,
        arabicText: 'أَمَّا مَنِ اسْتَغْنَىٰ',
        transliteration: 'Амма манистагна',
        russianText: 'Тому, кто счёл себя богатым',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5764,
        arabicText: 'فَأَنتَ لَهُۥ تَصَدَّىٰ',
        transliteration: 'фаанта ляху тасадда',
        russianText: 'ты оказываешь внимание',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5765,
        arabicText: 'وَمَا عَلَيْكَ أَلَّا يَزَّكَّىٰ',
        transliteration: "Ва ма 'алейка алля язакка",
        russianText: 'Что же с тебя, если он не очистится?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5766,
        arabicText: 'وَأَمَّا مَن جَآءَكَ يَسْعَىٰ',
        transliteration: "Ва амма ман джаака яс'а",
        russianText: 'А того, кто пришёл к тебе со рвением',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5767,
        arabicText: 'وَهُوَ يَخْشَىٰ',
        transliteration: 'ва хува яхша',
        russianText: 'и страшится Аллаха',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5768,
        arabicText: 'فَأَنتَ عَنْهُ تَلَهَّىٰ',
        transliteration: "фаанта 'анху талахха",
        russianText: 'ты оставляешь без внимания',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5769,
        arabicText: 'كَلَّآ إِنَّهَا تَذْكِرَةٌۭ',
        transliteration: 'Калля иннаха тазкира',
        russianText: 'Но нет! Это — Назидание',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5770,
        arabicText: 'فَمَن شَآءَ ذَكَرَهُۥ',
        transliteration: 'фаман шаа закараху',
        russianText: 'и пусть помянет его всякий желающий',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5771,
        arabicText: 'فِى صُحُفٍۢ مُّكَرَّمَةٍۢ',
        transliteration: 'Фи сухуфим мукаррама',
        russianText: 'Оно записано в почитаемых свитках',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5772,
        arabicText: 'مَّرْفُوعَةٍۢ مُّطَهَّرَةٍۭ',
        transliteration: "Марфу'атим мутаххара",
        russianText: 'вознесённых и очищенных',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5773,
        arabicText: 'بِأَيْدِى سَفَرَةٍۢ',
        transliteration: 'Биайди сафара',
        russianText: 'в руках посланцев',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5774,
        arabicText: 'كِرَامٍۭ بَرَرَةٍۢ',
        transliteration: 'Кирамим барара',
        russianText: 'благородных и покорных',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5775,
        arabicText: 'قُتِلَ الْإِنسَٰنُ مَآ أَكْفَرَهُۥ',
        transliteration: 'Кутиляль-инсану ма акфараху',
        russianText: 'Да сгинет человек! Как же он неблагодарен!',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5776,
        arabicText: 'مِنْ أَىِّ شَىْءٍ خَلَقَهُۥ',
        transliteration: 'Мин аййи шайин халякаху',
        russianText: 'Из чего Он сотворил его?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5777,
        arabicText: 'مِن نُّطْفَةٍ خَلَقَهُۥ فَقَدَّرَهُۥ',
        transliteration: 'Мин нутфатин халякаху факаддараху',
        russianText: 'Он сотворил его из капли и соразмерил',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5778,
        arabicText: 'ثُمَّ السَّبِيلَ يَسَّرَهُۥ',
        transliteration: 'Суммас-сабиля яссараху',
        russianText: 'потом облегчил ему путь',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5779,
        arabicText: 'ثُمَّ أَمَاتَهُۥ فَأَقْبَرَهُۥ',
        transliteration: 'Сумма аматаху фаакбараху',
        russianText: 'потом умертвил его и поместил в могилу',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5780,
        arabicText: 'ثُمَّ إِذَا شَآءَ أَنشَرَهُۥ',
        transliteration: 'Сумма иза шаа аншараху',
        russianText: 'а потом воскресит его, когда пожелает',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5781,
        arabicText: 'كَلَّا لَمَّا يَقْضِ مَآ أَمَرَهُۥ',
        transliteration: 'Калля лямма якди ма амараху',
        russianText: 'Но нет! Он не выполнил того, что Он повелел ему',
      ),
      LessonStep(
        type: LessonStepType.listenChoice,
        quranGlobalAyahNumber: 5759,
        arabicText: 'عَبَسَ وَتَوَلَّىٰٓ',
        question: 'Прослушай аят и выбери его перевод',
        answers: [
          'Он нахмурился и отвернулся',
          'Да сгинет человек! Как же он неблагодарен!',
          'Но нет! Это — Назидание',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.wordOrder,
        question: 'Собери аят 18 суры Абаса',
        russianText: 'Из чего Он сотворил его?',
        orderTokens: [
          'مِنْ',
          'أَىِّ',
          'شَىْءٍ',
          'خَلَقَهُۥ',
        ],
        extraTokens: [
          'السَّبِيلَ',
        ],
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'О чём напоминает начало суры Абаса?',
        answers: [
          'Искренне ищущий знание дороже равнодушного богача',
          'Богатым нужно уделять больше внимания',
          'Слепым нельзя учиться',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Как сура называет Коран в аяте 11?',
        answers: [
          'Назиданием',
          'Наказанием',
          'Загадкой',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Где, по суре, записано это Назидание?',
        answers: [
          'В почитаемых, вознесённых и очищенных свитках',
          'На камнях Каабы',
          'В памяти арабских поэтов',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Он сотворил его из ___ и соразмерил»',
        answers: [
          'капли',
          'глины',
          'огня',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Какой порядок жизни человека описывают аяты 19–22?',
        answers: [
          'Сотворение, облегчение пути, смерть и могила, затем воскрешение',
          'Рождение, богатство, слава',
          'Сон, бодрствование, работа',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: "'Абаса ва тавалля",
              answer: 'Он нахмурился и отвернулся'),
          LessonMatchPair(
              prompt: 'Калля иннаха тазкира',
              answer: 'Но нет! Это — Назидание'),
          LessonMatchPair(
              prompt: 'Кутиляль-инсану ма акфараху',
              answer: 'Да сгинет человек! Как же он неблагодарен!'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5759,
        arabicText: 'عَبَسَ وَتَوَلَّىٰٓ',
        transliteration: "'Абаса ва тавалля",
        russianText: 'Расскажи первый аят суры Абаса.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_abasa_2',
    title: 'Абаса, часть 2',
    subtitle: 'Аяты 24–42 • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 41,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Вторая половина суры зовёт человека посмотреть на собственную еду: дождь, рассечённая земля, зёрна, виноград, маслины, пальмы, сады и пастбища — всё это дар Аллаха. А затем — Оглушительный глас, в день которого человек убежит от брата, матери, отца, жены и детей: у каждого будет своя забота. Одни лица засияют, другие покроются пылью.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5782,
        arabicText: 'فَلْيَنظُرِ الْإِنسَٰنُ إِلَىٰ طَعَامِهِۦٓ',
        transliteration: "Фальянзуриль-инсану иля та'амихи",
        russianText: 'Пусть посмотрит человек на своё пропитание',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5783,
        arabicText: 'أَنَّا صَبَبْنَا الْمَآءَ صَبًّۭا',
        transliteration: 'Анна сабабналь-маа сабба',
        russianText: 'Мы проливаем воду обильно',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5784,
        arabicText: 'ثُمَّ شَقَقْنَا الْأَرْضَ شَقًّۭا',
        transliteration: 'Сумма шакакналь-арда шакка',
        russianText: 'потом рассекаем землю трещинами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5785,
        arabicText: 'فَأَنۢبَتْنَا فِيهَا حَبًّۭا',
        transliteration: 'Фаамбатна фиха хабба',
        russianText: 'и взращиваем на ней зёрна',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5786,
        arabicText: 'وَعِنَبًۭا وَقَضْبًۭا',
        transliteration: "Ва 'инабан ва кадба",
        russianText: 'виноград и травы',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5787,
        arabicText: 'وَزَيْتُونًۭا وَنَخْلًۭا',
        transliteration: 'Ва зайтунан ва нахля',
        russianText: 'маслины и пальмы',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5788,
        arabicText: 'وَحَدَآئِقَ غُلْبًۭا',
        transliteration: 'Ва хадаика гульба',
        russianText: 'густые сады',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5789,
        arabicText: 'وَفَٰكِهَةًۭ وَأَبًّۭا',
        transliteration: 'Ва факихатан ва абба',
        russianText: 'фрукты и пастбища',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5790,
        arabicText: 'مَّتَٰعًۭا لَّكُمْ وَلِأَنْعَٰمِكُمْ',
        transliteration: "Мата'ал лякум ва ли ан'амикум",
        russianText: 'на пользу вам и вашему скоту',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5791,
        arabicText: 'فَإِذَا جَآءَتِ الصَّآخَّةُ',
        transliteration: 'Фаиза джаатис-саххa',
        russianText: 'Когда же раздастся Оглушительный глас',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5792,
        arabicText: 'يَوْمَ يَفِرُّ الْمَرْءُ مِنْ أَخِيهِ',
        transliteration: "Яума яфирруль-мар'у мин ахих",
        russianText: 'в тот день человек убежит от своего брата',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5793,
        arabicText: 'وَأُمِّهِۦ وَأَبِيهِ',
        transliteration: 'Ва уммихи ва абих',
        russianText: 'от матери и отца',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5794,
        arabicText: 'وَصَٰحِبَتِهِۦ وَبَنِيهِ',
        transliteration: 'Ва сахибатихи ва баних',
        russianText: 'от жены и детей',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5795,
        arabicText: 'لِكُلِّ امْرِئٍۢ مِّنْهُمْ يَوْمَئِذٍۢ شَأْنٌۭ يُغْنِيهِ',
        transliteration: "Ликуллим-риим минхум яумаизин ша'нуй югних",
        russianText:
            'У каждого человека в тот день будет забота, которой ему хватит сполна',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5796,
        arabicText: 'وُجُوهٌۭ يَوْمَئِذٍۢ مُّسْفِرَةٌۭ',
        transliteration: 'Вуджухуй яумаизим мусфира',
        russianText: 'Одни лица в тот день будут сиять',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5797,
        arabicText: 'ضَاحِكَةٌۭ مُّسْتَبْشِرَةٌۭ',
        transliteration: 'Дахикатум мустабшира',
        russianText: 'смеяться и ликовать',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5798,
        arabicText: 'وَوُجُوهٌۭ يَوْمَئِذٍ عَلَيْهَا غَبَرَةٌۭ',
        transliteration: "Ва вуджухуй яумаизин 'алейха габара",
        russianText: 'На других лицах в тот день будет пыль',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5799,
        arabicText: 'تَرْهَقُهَا قَتَرَةٌ',
        transliteration: 'Тархакуха катара',
        russianText: 'покрывающая их мраком',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5800,
        arabicText: 'أُو۟لَٰٓئِكَ هُمُ الْكَفَرَةُ الْفَجَرَةُ',
        transliteration: 'Уляика хумуль-кафаратуль-фаджара',
        russianText: 'Это — неверующие грешники',
      ),
      LessonStep(
        type: LessonStepType.listenChoice,
        quranGlobalAyahNumber: 5782,
        arabicText: 'فَلْيَنظُرِ الْإِنسَٰنُ إِلَىٰ طَعَامِهِۦٓ',
        question: 'Прослушай аят и выбери его перевод',
        answers: [
          'Пусть посмотрит человек на своё пропитание',
          'Пусть посмотрит человек, из чего он создан',
          'Мы проливаем воду обильно',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.wordOrder,
        question: 'Собери аят 34 суры Абаса',
        russianText: 'в тот день человек убежит от своего брата',
        orderTokens: [
          'يَوْمَ',
          'يَفِرُّ',
          'الْمَرْءُ',
          'مِنْ',
          'أَخِيهِ',
        ],
        extraTokens: [
          'وَأَبِيهِ',
        ],
      ),
      LessonStep(
        type: LessonStepType.question,
        question:
            'К чему призывает аят «Пусть посмотрит человек на своё пропитание»?',
        answers: [
          'Увидеть в обычной еде знамение и дар Аллаха',
          'Есть только растительную пищу',
          'Считать калории',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Что происходит по порядку в аятах 25–26?',
        answers: [
          'Проливается вода, затем рассекается земля',
          'Сначала растут деревья, потом идёт дождь',
          'Земля высыхает и трескается от жары',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'От кого человек убежит в день Оглушительного гласа?',
        answers: [
          'От брата, матери, отца, жены и детей',
          'Только от врагов',
          'От правителей',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Почему в тот день каждому будет не до других?',
        answers: [
          'У каждого будет своя забота, которой хватит сполна',
          'Все будут спать',
          'Никто не будет узнавать друг друга по именам',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем сура противопоставляет две группы лиц в конце?',
        answers: [
          'Сияющие и смеющиеся — против покрытых пылью и мраком',
          'Молодые — против старых',
          'Богатые — против бедных',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: "Фальянзуриль-инсану иля та'амихи",
              answer: 'Пусть посмотрит человек на своё пропитание'),
          LessonMatchPair(
              prompt: 'Вуджухуй яумаизим мусфира',
              answer: 'Одни лица в тот день будут сиять'),
          LessonMatchPair(
              prompt: 'Уляика хумуль-кафаратуль-фаджара',
              answer: 'Это — неверующие грешники'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5782,
        arabicText: 'فَلْيَنظُرِ الْإِنسَٰنُ إِلَىٰ طَعَامِهِۦٓ',
        transliteration: "Фальянзуриль-инсану иля та'амихи",
        russianText: 'Расскажи аят 24 суры Абаса.',
      ),
    ],
  ),
  const Lesson(
    id: 'q_takwir_1',
    title: 'Ат-Таквир',
    subtitle: 'Аяты 1–29 • полный текст во вкладке «Коран»',
    course: CourseType.quran,
    order: 42,
    steps: [
      LessonStep(
        type: LessonStepType.text,
        russianText:
            'Ат-Таквир означает «Свёртывание». Первая половина суры двенадцатью «когда» рисует картину конца света: свёрнутое солнце, осыпавшиеся звёзды, сдвинутые горы, запылавшие моря — и вопрос к убитой живьём девочке, за какой грех её убили. Вторая половина клянётся звёздами, ночью и зарёй, защищая Пророка ﷺ: Коран — слово благородного посланца, а не речи дьявола.',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5801,
        arabicText: 'إِذَا الشَّمْسُ كُوِّرَتْ',
        transliteration: 'Изаш-шамсу куввират',
        russianText: 'Когда солнце будет свёрнуто',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5802,
        arabicText: 'وَإِذَا النُّجُومُ انكَدَرَتْ',
        transliteration: 'ва изан-нуджумун-кадарат',
        russianText: 'когда звёзды осыплются',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5803,
        arabicText: 'وَإِذَا الْجِبَالُ سُيِّرَتْ',
        transliteration: 'ва изаль-джибалю суййират',
        russianText: 'когда горы сдвинутся с мест',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5804,
        arabicText: 'وَإِذَا الْعِشَارُ عُطِّلَتْ',
        transliteration: "ва изаль-'ишару 'уттылят",
        russianText: 'когда верблюдицы на сносях останутся без присмотра',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5805,
        arabicText: 'وَإِذَا الْوُحُوشُ حُشِرَتْ',
        transliteration: 'ва изаль-вухушу хушират',
        russianText: 'когда дикие звери будут собраны',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5806,
        arabicText: 'وَإِذَا الْبِحَارُ سُجِّرَتْ',
        transliteration: 'ва изаль-бихару суджджират',
        russianText: 'когда моря запылают',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5807,
        arabicText: 'وَإِذَا النُّفُوسُ زُوِّجَتْ',
        transliteration: 'ва изан-нуфусу зуввиджат',
        russianText: 'когда души будут распределены по парам',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5808,
        arabicText: 'وَإِذَا الْمَوْءُۥدَةُ سُئِلَتْ',
        transliteration: "ва изаль-мау'удату суилят",
        russianText: 'когда зарытую живьём девочку спросят',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5809,
        arabicText: 'بِأَىِّ ذَنۢبٍۢ قُتِلَتْ',
        transliteration: 'биаййи занбин кутилят',
        russianText: 'за какой грех она была убита',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5810,
        arabicText: 'وَإِذَا الصُّحُفُ نُشِرَتْ',
        transliteration: 'ва изас-сухуфу нушират',
        russianText: 'когда свитки дел будут развёрнуты',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5811,
        arabicText: 'وَإِذَا السَّمَآءُ كُشِطَتْ',
        transliteration: 'ва изас-самау кушитат',
        russianText: 'когда небо будет сдёрнуто',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5812,
        arabicText: 'وَإِذَا الْجَحِيمُ سُعِّرَتْ',
        transliteration: "ва изаль-джахиму су'ират",
        russianText: 'когда Ад будет разожжён',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5813,
        arabicText: 'وَإِذَا الْجَنَّةُ أُزْلِفَتْ',
        transliteration: 'ва изаль-джаннату узлифат',
        russianText: 'когда Рай будет приближен',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5814,
        arabicText: 'عَلِمَتْ نَفْسٌۭ مَّآ أَحْضَرَتْ',
        transliteration: "'алимат нафсум ма ахдарат",
        russianText: 'тогда познает душа, что она принесла с собой',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5815,
        arabicText: 'فَلَآ أُقْسِمُ بِالْخُنَّسِ',
        transliteration: 'Фаля уксиму биль-хуннас',
        russianText: 'Клянусь отступающими планетами',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5816,
        arabicText: 'الْجَوَارِ الْكُنَّسِ',
        transliteration: 'аль-джавариль-куннас',
        russianText: 'движущимися и исчезающими',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5817,
        arabicText: 'وَالَّيْلِ إِذَا عَسْعَسَ',
        transliteration: "валь-лейли иза 'ас'ас",
        russianText: 'Клянусь ночью, когда она отступает',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5818,
        arabicText: 'وَالصُّبْحِ إِذَا تَنَفَّسَ',
        transliteration: 'вас-субхи иза танаффас',
        russianText: 'и зарёй, когда она забрезжит',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5819,
        arabicText: 'إِنَّهُۥ لَقَوْلُ رَسُولٍۢ كَرِيمٍۢ',
        transliteration: 'Иннаху лякаулю расулин карим',
        russianText: 'Воистину, это — слово благородного посланца',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5820,
        arabicText: 'ذِى قُوَّةٍ عِندَ ذِى الْعَرْشِ مَكِينٍۢ',
        transliteration: "зи куввaтин 'инда зиль-'арши макин",
        russianText: 'обладателя силы при Владыке Трона, могущественного',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5821,
        arabicText: 'مُّطَاعٍۢ ثَمَّ أَمِينٍۢ',
        transliteration: "мута'ин самма амин",
        russianText: 'которому там повинуются, доверенного',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5822,
        arabicText: 'وَمَا صَاحِبُكُم بِمَجْنُونٍۢ',
        transliteration: 'Ва ма сахибукум бимаджнун',
        russianText: 'Ваш товарищ не является одержимым',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5823,
        arabicText: 'وَلَقَدْ رَءَاهُ بِالْأُفُقِ الْمُبِينِ',
        transliteration: 'Ва лякад рааху биль-уфукиль-мубин',
        russianText: 'Он видел его на ясном горизонте',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5824,
        arabicText: 'وَمَا هُوَ عَلَى الْغَيْبِ بِضَنِينٍۢ',
        transliteration: "Ва ма хува 'аляль-гайби бидaнин",
        russianText: 'Он не скупится передавать сокровенное',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5825,
        arabicText: 'وَمَا هُوَ بِقَوْلِ شَيْطَٰنٍۢ رَّجِيمٍۢ',
        transliteration: 'Ва ма хува бикаули шайтанир-раджим',
        russianText: 'Это не речи побиваемого дьявола',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5826,
        arabicText: 'فَأَيْنَ تَذْهَبُونَ',
        transliteration: 'Фаайна тазхабун',
        russianText: 'Куда же вы идёте?',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5827,
        arabicText: 'إِنْ هُوَ إِلَّا ذِكْرٌۭ لِّلْعَٰلَمِينَ',
        transliteration: "Ин хува илля зикрул лиль-'алямин",
        russianText: 'Это — лишь Напоминание мирам',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5828,
        arabicText: 'لِمَن شَآءَ مِنكُمْ أَن يَسْتَقِيمَ',
        transliteration: 'лиман шаа минкум ай ястаким',
        russianText: 'тем из вас, кто желает следовать прямым путём',
      ),
      LessonStep(
        type: LessonStepType.audio,
        quranGlobalAyahNumber: 5829,
        arabicText:
            'وَمَا تَشَآءُونَ إِلَّآ أَن يَشَآءَ اللَّهُ رَبُّ الْعَٰلَمِينَ',
        transliteration: "Ва ма ташаууна илля ай яшааллаху раббуль-'алямин",
        russianText:
            'Но вы не пожелаете этого, если не пожелает Аллах, Господь миров',
      ),
      LessonStep(
        type: LessonStepType.listenChoice,
        quranGlobalAyahNumber: 5801,
        arabicText: 'إِذَا الشَّمْسُ كُوِّرَتْ',
        question: 'Прослушай аят и выбери его перевод',
        answers: [
          'Когда солнце будет свёрнуто',
          'Когда небо расколется',
          'Когда земля содрогнётся от сотрясения',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.wordOrder,
        question: 'Собери аят 19 суры Ат-Таквир',
        russianText: 'Воистину, это — слово благородного посланца',
        orderTokens: [
          'إِنَّهُۥ',
          'لَقَوْلُ',
          'رَسُولٍۢ',
          'كَرِيمٍۢ',
        ],
        extraTokens: [
          'رَّجِيمٍۢ',
        ],
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Что означает название суры Ат-Таквир?',
        answers: [
          'Свёртывание — солнце будет свёрнуто',
          'Раскалывание неба',
          'Ночной путник',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'О чём спросят зарытую живьём девочку в аятах 8–9?',
        answers: [
          'За какой грех она была убита',
          'Кто её родители',
          'Где она жила',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Заполни пропуск: «Тогда познает душа, что она ___»',
        answers: [
          'принесла с собой',
          'забыла дома',
          'услышала от людей',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Как сура отвечает на обвинения в адрес Пророка ﷺ?',
        answers: [
          'Ваш товарищ не одержимый, а Коран — не речи дьявола',
          'Пророк не обязан отвечать',
          'Обвинителям обещана награда',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.question,
        question: 'Чем завершается сура Ат-Таквир?',
        answers: [
          'Напоминанием, что желание человека следует воле Господа миров',
          'Клятвой смоковницей и оливой',
          'Повелением сражаться',
        ],
        correctAnswerIndex: 0,
      ),
      LessonStep(
        type: LessonStepType.matching,
        question: 'Соедини транслитерацию и перевод',
        matchPairs: [
          LessonMatchPair(
              prompt: 'Изаш-шамсу куввират',
              answer: 'Когда солнце будет свёрнуто'),
          LessonMatchPair(
              prompt: 'Фаайна тазхабун', answer: 'Куда же вы идёте?'),
          LessonMatchPair(
              prompt: 'Ва ма сахибукум бимаджнун',
              answer: 'Ваш товарищ не является одержимым'),
        ],
      ),
      LessonStep(
        type: LessonStepType.speak,
        quranGlobalAyahNumber: 5801,
        arabicText: 'إِذَا الشَّمْسُ كُوِّرَتْ',
        transliteration: 'Изаш-шамсу куввират',
        russianText: 'Расскажи первый аят суры Ат-Таквир.',
      ),
    ],
  ),
];
