// Retires the root-scoped cache worker generated by older Flutter releases.
// Push notifications use /push/muslingo_push_sw.js with a separate /push/
// scope and are intentionally left untouched.
const LEGACY_FLUTTER_CACHES = new Set([
  'flutter-app-cache',
  'flutter-temp-cache',
  'flutter-app-manifest',
]);

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const cacheNames = await caches.keys();
    await Promise.all(cacheNames
      .filter((name) => LEGACY_FLUTTER_CACHES.has(name))
      .map((name) => caches.delete(name)));

    await self.clients.claim();
    const windows = await self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    });
    await self.registration.unregister();
    await Promise.all(windows.map((client) => client.navigate(client.url)));
  })());
});
